CREATE TABLE animal (
  id CHAR(36) NOT NULL,
  campus_id CHAR(36) NOT NULL,
  display_name VARCHAR(80) NOT NULL,
  species VARCHAR(32) NOT NULL,
  sex VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  coat_color VARCHAR(120) NULL,
  distinctive_features VARCHAR(1000) NULL,
  description VARCHAR(2000) NULL,
  sterilization_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  typical_area VARCHAR(255) NULL,
  identity_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  adoption_status VARCHAR(32) NOT NULL DEFAULT 'NOT_OPEN',
  current_context VARCHAR(32) NOT NULL DEFAULT 'CAMPUS',
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_animal_campus_identity_name (campus_id, identity_status, display_name, id),
  KEY idx_animal_campus_species_identity (campus_id, species, identity_status, id),
  CONSTRAINT chk_animal_species CHECK (species IN ('CAT', 'DOG', 'OTHER')),
  CONSTRAINT chk_animal_sex CHECK (sex IN ('MALE', 'FEMALE', 'UNKNOWN')),
  CONSTRAINT chk_animal_sterilization CHECK (sterilization_status IN ('STERILIZED', 'NOT_STERILIZED', 'UNKNOWN')),
  CONSTRAINT chk_animal_identity_status CHECK (identity_status IN ('ACTIVE', 'MERGED', 'ARCHIVED')),
  CONSTRAINT chk_animal_adoption_status CHECK (adoption_status IN ('NOT_OPEN', 'OPEN', 'HANDOVER_PENDING', 'ADOPTED')),
  CONSTRAINT chk_animal_current_context CHECK (current_context IN ('CAMPUS', 'ADOPTED_HOME'))
) ENGINE=InnoDB;

CREATE TABLE animal_media (
  id CHAR(36) NOT NULL,
  animal_id CHAR(36) NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  content_type VARCHAR(120) NOT NULL,
  media_type VARCHAR(32) NOT NULL,
  size_bytes BIGINT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_animal_media_object_key (object_key),
  KEY idx_animal_media_animal_order (animal_id, sort_order, id),
  CONSTRAINT fk_animal_media_animal FOREIGN KEY (animal_id) REFERENCES animal (id),
  CONSTRAINT chk_animal_media_type CHECK (media_type IN ('IMAGE', 'VIDEO')),
  CONSTRAINT chk_animal_media_visibility CHECK (visibility IN ('PUBLIC', 'RESTRICTED')),
  CONSTRAINT chk_animal_media_size CHECK (size_bytes IS NULL OR size_bytes >= 0),
  CONSTRAINT chk_animal_media_sort CHECK (sort_order >= 0)
) ENGINE=InnoDB;

CREATE TABLE timeline_entry (
  id CHAR(36) NOT NULL,
  animal_id CHAR(36) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_id CHAR(36) NOT NULL,
  entry_type VARCHAR(64) NOT NULL,
  title VARCHAR(160) NOT NULL,
  summary VARCHAR(1000) NULL,
  occurred_at DATETIME(6) NOT NULL,
  visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_timeline_source (source_type, source_id),
  KEY idx_timeline_animal_occurred (animal_id, occurred_at DESC, id DESC),
  CONSTRAINT fk_timeline_animal FOREIGN KEY (animal_id) REFERENCES animal (id),
  CONSTRAINT chk_timeline_visibility CHECK (visibility IN ('PUBLIC', 'RESTRICTED'))
) ENGINE=InnoDB;
