package org.animallink.adoption.infrastructure;
import java.sql.Timestamp; import java.util.*; import org.animallink.adoption.application.AdoptionHandoverRepository; import org.animallink.adoption.domain.*; import org.springframework.jdbc.core.*; import org.springframework.stereotype.Repository;
@Repository public class JdbcAdoptionHandoverRepository implements AdoptionHandoverRepository{
 private final JdbcTemplate jdbc; public JdbcAdoptionHandoverRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private static final RowMapper<AdoptionHandover> ROW=(r,n)->new AdoptionHandover(r.getString("id"),r.getString("selection_id"),HandoverStatus.valueOf(r.getString("status")),r.getTimestamp("scheduled_at").toInstant(),r.getString("initiated_by_user_id"),r.getTimestamp("initiated_at").toInstant(),r.getString("note"),r.getString("completed_by_user_id"),instant(r,"completed_at"),r.getString("cancelled_by_user_id"),instant(r,"cancelled_at"),r.getString("cancel_reason"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());
 private static java.time.Instant instant(java.sql.ResultSet r,String c)throws java.sql.SQLException{Timestamp v=r.getTimestamp(c);return v==null?null:v.toInstant();}
 public void insert(AdoptionHandover v){jdbc.update("INSERT INTO adoption_handover(id,selection_id,status,scheduled_at,initiated_by_user_id,initiated_at,note,created_at,updated_at) VALUES(?,?,?, ?,?,?,?, ?,?)",v.id(),v.selectionId(),v.status().name(),Timestamp.from(v.scheduledAt()),v.initiatedByUserId(),Timestamp.from(v.initiatedAt()),v.note(),Timestamp.from(v.createdAt()),Timestamp.from(v.updatedAt()));}
 public Optional<AdoptionHandover> findById(String id){return jdbc.query("SELECT * FROM adoption_handover WHERE id=?",ROW,id).stream().findFirst();} public Optional<AdoptionHandover> findBySelectionId(String id){return jdbc.query("SELECT * FROM adoption_handover WHERE selection_id=?",ROW,id).stream().findFirst();}
 public boolean complete(String id,String u,java.time.Instant at){return jdbc.update("UPDATE adoption_handover SET status='COMPLETED',completed_by_user_id=?,completed_at=?,updated_at=? WHERE id=? AND status='PENDING'",u,Timestamp.from(at),Timestamp.from(at),id)==1;}
 public boolean cancel(String id,String u,java.time.Instant at,String reason){return jdbc.update("UPDATE adoption_handover SET status='CANCELLED',cancelled_by_user_id=?,cancelled_at=?,cancel_reason=?,updated_at=? WHERE id=? AND status='PENDING'",u,Timestamp.from(at),reason,Timestamp.from(at),id)==1;}
 public void insertRelation(AdoptionRelation r){jdbc.update("INSERT INTO adoption_relation(id,animal_id,adopter_user_id,handover_id,status,activated_at,created_at,updated_at) VALUES(?,?,?,?, 'ACTIVE',?,?,?)",r.id(),r.animalId(),r.adopterUserId(),r.handoverId(),Timestamp.from(r.activatedAt()),Timestamp.from(r.activatedAt()),Timestamp.from(r.activatedAt()));}
 public Optional<AdoptionRelation> relationByHandover(String h){return jdbc.query("SELECT id,animal_id,adopter_user_id,handover_id,status,activated_at,ended_at,end_reason FROM adoption_relation WHERE handover_id=?",this::relation,h).stream().findFirst();}
 public Optional<AdoptionRelation> findRelationById(String id){return jdbc.query("SELECT id,animal_id,adopter_user_id,handover_id,status,activated_at,ended_at,end_reason FROM adoption_relation WHERE id=?",this::relation,id).stream().findFirst();}
 public Optional<AdoptionRelation> findRelationByIdForUpdate(String id){return jdbc.query("SELECT id,animal_id,adopter_user_id,handover_id,status,activated_at,ended_at,end_reason FROM adoption_relation WHERE id=? FOR UPDATE",this::relation,id).stream().findFirst();}
 public Optional<AdoptionRelation> findActiveRelationByAnimalAndAdopter(String animalId,String adopterUserId){List<AdoptionRelation> matches=jdbc.query("SELECT id,animal_id,adopter_user_id,handover_id,status,activated_at,ended_at,end_reason FROM adoption_relation WHERE animal_id=? AND adopter_user_id=? AND status='ACTIVE'",this::relation,animalId,adopterUserId);if(matches.size()>1)throw new IllegalStateException("同一 Animal 存在多个 ACTIVE AdoptionRelation");return matches.stream().findFirst();}
 public boolean endRelation(String id,java.time.Instant endedAt,String reason){return jdbc.update("UPDATE adoption_relation SET status='ENDED',ended_at=?,end_reason=?,updated_at=? WHERE id=? AND status='ACTIVE'",Timestamp.from(endedAt),reason,Timestamp.from(endedAt),id)==1;}
 public void insertOutbox(String id,String relationId,String eventType,String payload,java.time.Instant at){jdbc.update("INSERT INTO outbox_event(id,aggregate_type,aggregate_id,event_type,payload_json,status,available_at,created_at,updated_at) VALUES(?,'ADOPTION_RELATION',?,?,CAST(? AS JSON),'PENDING',?,?,?)",id,relationId,eventType,payload,Timestamp.from(at),Timestamp.from(at),Timestamp.from(at));}
 public List<ApplicantHandover> findByApplicant(String user){return jdbc.query("SELECT h.*,s.listing_id,s.application_id FROM adoption_handover h JOIN adoption_selection s ON s.id=h.selection_id JOIN adoption_application a ON a.id=s.application_id WHERE a.applicant_user_id=? ORDER BY h.initiated_at DESC,h.id DESC",(r,n)->new ApplicantHandover(ROW.mapRow(r,n),r.getString("listing_id"),r.getString("application_id")),user);}
 private AdoptionRelation relation(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new AdoptionRelation(r.getString("id"),r.getString("animal_id"),r.getString("adopter_user_id"),r.getString("handover_id"),r.getString("status"),r.getTimestamp("activated_at").toInstant(),instant(r,"ended_at"),r.getString("end_reason"));}
}
