package org.animallink.animal;

import com.fasterxml.jackson.databind.ObjectMapper; import java.time.Instant; import java.util.UUID; import java.util.concurrent.*; import org.animallink.animal.infrastructure.AdoptionCompletedAnimalConsumer; import org.junit.jupiter.api.*; import org.springframework.amqp.AmqpRejectAndDontRequeueException; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.*; import org.springframework.boot.test.mock.mockito.SpyBean; import org.springframework.context.annotation.*; import org.springframework.dao.DataAccessResourceFailureException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.*; import org.testcontainers.containers.MySQLContainer; import org.testcontainers.junit.jupiter.*; import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest @Testcontainers @Import(AdoptionCompletedAnimalConsumerIntegrationTest.Config.class) class AdoptionCompletedAnimalConsumerIntegrationTest{
 static final String A="20000000-0000-0000-0000-000000000004"; @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("adoption_completed_test").withUsername("test").withPassword("test");
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);}
 @SpyBean JdbcTemplate jdbc; @Autowired AdoptionCompletedAnimalConsumer consumer;
 @BeforeEach void clean(){jdbc.update("DELETE FROM processed_domain_event");jdbc.update("DELETE FROM timeline_entry");jdbc.update("DELETE FROM animal");jdbc.update("INSERT INTO animal(id,campus_id,display_name,species,sex,identity_status,adoption_status,current_context) VALUES(?,'c','a','CAT','UNKNOWN','ACTIVE','OPEN','CAMPUS')",A);}
 @Test void validEventTransitionsTimelineAndMarker(){String e=event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A);consumer.consume(e);assertEquals("ADOPTED",jdbc.queryForObject("SELECT adoption_status FROM animal WHERE id=?",String.class,A));assertEquals("ADOPTED_HOME",jdbc.queryForObject("SELECT current_context FROM animal WHERE id=?",String.class,A));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry WHERE source_type='ADOPTION'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event",Integer.class));}
 @Test void contractsAndInvalidAnimalRejectWithoutMarker(){assertThrows(AmqpRejectAndDontRequeueException.class,()->consumer.consume("{}"));jdbc.update("UPDATE animal SET identity_status='ARCHIVED' WHERE id=?",A);assertThrows(AmqpRejectAndDontRequeueException.class,()->consumer.consume(event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A)));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event",Integer.class));}
 @Test void sameEventIsIdempotentAndDifferentEventConflicts(){String first=event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A);consumer.consume(first);consumer.consume(first);assertThrows(AmqpRejectAndDontRequeueException.class,()->consumer.consume(event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A)));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event",Integer.class));}
 @Test void timelineWriteFailureRollsBackAnimalAndProcessedEventThenRetries() {String id=UUID.randomUUID().toString(),relation=UUID.randomUUID().toString(),e=event(id,relation,A);org.mockito.Mockito.doAnswer(x->{if(x.getArgument(0,String.class).startsWith("INSERT INTO timeline_entry"))throw new DataAccessResourceFailureException("transient timeline failure");return x.callRealMethod();}).when(jdbc).update(org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.any(Object[].class));assertThrows(DataAccessResourceFailureException.class,()->consumer.consume(e));assertEquals("OPEN",jdbc.queryForObject("SELECT adoption_status FROM animal WHERE id=?",String.class,A));assertEquals("CAMPUS",jdbc.queryForObject("SELECT current_context FROM animal WHERE id=?",String.class,A));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event WHERE event_id=?",Integer.class,id));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry WHERE source_id=?",Integer.class,relation));org.mockito.Mockito.reset(jdbc);consumer.consume(e);assertEquals("ADOPTED",jdbc.queryForObject("SELECT adoption_status FROM animal WHERE id=?",String.class,A));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event WHERE event_id=?",Integer.class,id));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry WHERE source_id=?",Integer.class,relation));}
 @RepeatedTest(10) void concurrentSameEventConverges()throws Exception{String e=event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A);race(()->consumer.consume(e),()->consumer.consume(e),false);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event",Integer.class));}
 @RepeatedTest(10) void concurrentDifferentEventsHaveOneWinner()throws Exception{race(()->consumer.consume(event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A)),()->consumer.consume(event(UUID.randomUUID().toString(),UUID.randomUUID().toString(),A)),true);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM timeline_entry",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM processed_domain_event",Integer.class));}
 void race(Runnable x,Runnable y,boolean oneReject)throws Exception{ExecutorService p=Executors.newFixedThreadPool(2);CountDownLatch s=new CountDownLatch(1),r=new CountDownLatch(2);Future<Boolean>a=p.submit(()->go(x,s,r)),b=p.submit(()->go(y,s,r));r.await();s.countDown();boolean u=a.get(),v=b.get();p.shutdown();assertEquals(oneReject?1:2,(u?1:0)+(v?1:0));}boolean go(Runnable x,CountDownLatch s,CountDownLatch r){r.countDown();try{s.await();x.run();return true;}catch(AmqpRejectAndDontRequeueException e){return false;}catch(Exception e){throw new RuntimeException(e);}}
 String event(String id,String relation,String animal){return "{\"eventId\":\""+id+"\",\"eventType\":\"ADOPTION_COMPLETED\",\"eventVersion\":1,\"occurredAt\":\"2026-10-05T00:00:00Z\",\"relationId\":\""+relation+"\",\"handoverId\":\""+UUID.randomUUID()+"\",\"animalId\":\""+animal+"\"}";}
 @TestConfiguration static class Config{@Bean AdoptionCompletedAnimalConsumer adoptionCompletedAnimalConsumer(JdbcTemplate j,ObjectMapper o){return new AdoptionCompletedAnimalConsumer(j,o);}}
}
