package org.animallink.incident.api;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;

@RestController
@RequestMapping("/api/v1/cases/{caseId}/participants")
public class CaseParticipantController {
  private final JdbcTemplate jdbc; private final RestClient identity; private final HttpServletRequest request;
  public CaseParticipantController(JdbcTemplate jdbc, @Qualifier("identityRestClient") RestClient identity, HttpServletRequest request) { this.jdbc=jdbc; this.identity=identity; this.request=request; }
  @PostMapping("/invitations") @Transactional public ParticipantResponse invite(@PathVariable("caseId") String caseId, @Valid @RequestBody InvitationRequest body) { String caller=user(); Map<String,Object> c=caseOne(caseId); activeCase(c); owner(c,caller); volunteer(caller,s(c,"campus_id")); if(caller.equals(body.userId())) throw new EventController.Conflict("CANNOT_INVITE_CASE_OWNER"); volunteer(body.userId(),s(c,"campus_id")); Instant now=Instant.now(); String id=UUID.randomUUID().toString(); try { jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES (?,?,?,'INVITED',?,?,?,?)",id,caseId,body.userId(),caller,Timestamp.from(now),Timestamp.from(now),Timestamp.from(now)); } catch (DuplicateKeyException e) { throw new EventController.Conflict("CASE_PARTICIPANT_EXISTS"); } return response(participantOne(id)); }
  @PostMapping("/{participantId}/accept") @Transactional public ParticipantResponse accept(@PathVariable("caseId") String caseId,@PathVariable("participantId") String participantId) { return targetTransition(caseId,participantId,"INVITED","ACTIVE",true); }
  @PostMapping("/{participantId}/decline") @Transactional public ParticipantResponse decline(@PathVariable("caseId") String caseId,@PathVariable("participantId") String participantId) { return targetTransition(caseId,participantId,"INVITED","DECLINED",false); }
  @PostMapping("/{participantId}/leave") @Transactional public ParticipantResponse leave(@PathVariable("caseId") String caseId,@PathVariable("participantId") String participantId) { return targetTransition(caseId,participantId,"ACTIVE","LEFT",false); }
  @PostMapping("/{participantId}/remove") @Transactional public ParticipantResponse remove(@PathVariable("caseId") String caseId,@PathVariable("participantId") String participantId) { String caller=user(); Map<String,Object> c=caseOne(caseId); activeCase(c); owner(c,caller); volunteer(caller,s(c,"campus_id")); participantForCase(caseId,participantId); Instant now=Instant.now(); int changed=jdbc.update("UPDATE case_participant SET status='REMOVED',ended_at=?,version=version+1,updated_at=? WHERE id=? AND case_id=? AND status='ACTIVE'",Timestamp.from(now),Timestamp.from(now),participantId,caseId); if(changed!=1) throw new EventController.Conflict("CASE_PARTICIPANT_STATE_CONFLICT"); return response(participantOne(participantId)); }
  @GetMapping public List<ParticipantResponse> list(@PathVariable("caseId") String caseId) { String caller=user(); Map<String,Object> c=caseOne(caseId); if(!caller.equals(s(c,"owner_user_id")) && !"GOVERNANCE_ADMIN".equals(role()) && !participantForUser(caseId,caller)) throw new EventController.Forbidden("CASE_PARTICIPANT_ACCESS_REQUIRED"); return jdbc.queryForList("SELECT * FROM case_participant WHERE case_id=? ORDER BY created_at,id",caseId).stream().map(this::response).toList(); }
  private ParticipantResponse targetTransition(String caseId,String participantId,String from,String to,boolean requiresActiveVolunteer) { String caller=user(); Map<String,Object> c=caseOne(caseId); if("ACTIVE".equals(to)) activeCase(c); Map<String,Object> p=participantForCase(caseId,participantId); if(!caller.equals(s(p,"user_id"))) throw new EventController.Forbidden("CASE_PARTICIPANT_TARGET_REQUIRED"); if(requiresActiveVolunteer) volunteer(caller,s(c,"campus_id")); Instant now=Instant.now(); String sql="UPDATE case_participant SET status=?,joined_at="+("ACTIVE".equals(to)?"?":"joined_at")+",ended_at="+("ACTIVE".equals(to)?"ended_at":"?")+",version=version+1,updated_at=? WHERE id=? AND case_id=? AND status=?"; List<Object> args=new ArrayList<>(); args.add(to); args.add(Timestamp.from(now)); args.add(Timestamp.from(now)); args.add(participantId); args.add(caseId); args.add(from); if(jdbc.update(sql,args.toArray())!=1) throw new EventController.Conflict("CASE_PARTICIPANT_STATE_CONFLICT"); return response(participantOne(participantId)); }
  private void activeCase(Map<String,Object> c) { if(!"ACTIVE".equals(s(c,"status"))||!"CLAIMED".equals(s(c,"claim_status"))) throw new EventController.Conflict("CASE_NOT_ACTIVE"); }
  private void owner(Map<String,Object> c,String user) { if(!user.equals(s(c,"owner_user_id"))) throw new EventController.Forbidden("CASE_OWNER_REQUIRED"); }
  private void volunteer(String user,String campus) { try { Map<?,?> f=identity.get().uri("/internal/v1/users/{u}/campuses/{c}/volunteer-membership",user,campus).header("X-Internal-Service","incident-service").retrieve().body(Map.class); if(f==null||!Boolean.TRUE.equals(f.get("exists"))||!Boolean.TRUE.equals(f.get("active"))||!"ACTIVE".equals(f.get("status"))) throw new EventController.Forbidden("ACTIVE_VOLUNTEER_REQUIRED"); } catch(EventController.Forbidden e) { throw e; } catch(Exception e) { throw new EventController.Dependency("IDENTITY_SERVICE_UNAVAILABLE"); } }
  private String user() { try { var spec=identity.get().uri("/api/v1/users/me"); String h=request.getHeader("X-User-Id"); if(h!=null) spec=spec.header("X-User-Id",h); Map<?,?> u=spec.retrieve().body(Map.class); if(u==null) throw new EventController.Unauthorized("需要登录"); return String.valueOf(u.get("id")); } catch(EventController.Unauthorized e) { throw e; } catch(Exception e) { throw new EventController.Unauthorized("需要登录"); } }
  private String role() { try { var spec=identity.get().uri("/api/v1/users/me"); String h=request.getHeader("X-User-Id"); if(h!=null) spec=spec.header("X-User-Id",h); Map<?,?> u=spec.retrieve().body(Map.class); return u==null?null:String.valueOf(u.get("systemRole")); } catch(Exception e) { throw new EventController.Unauthorized("需要登录"); } }
  private Map<String,Object> caseOne(String id) { List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM animal_case WHERE id=?",id); if(rows.isEmpty()) throw new EventController.NotFound("Case 不存在"); return rows.getFirst(); }
  private Map<String,Object> participantOne(String id) { List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM case_participant WHERE id=?",id); if(rows.isEmpty()) throw new EventController.NotFound("CASE_PARTICIPANT_NOT_FOUND"); return rows.getFirst(); }
  private Map<String,Object> participantForCase(String caseId,String id) { List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM case_participant WHERE id=? AND case_id=?",id,caseId); if(rows.isEmpty()) throw new EventController.NotFound("CASE_PARTICIPANT_NOT_FOUND"); return rows.getFirst(); }
  private boolean participantForUser(String caseId,String user) { Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM case_participant WHERE case_id=? AND user_id=? AND status='ACTIVE'",Integer.class,caseId,user); return count!=null&&count>0; }
  private ParticipantResponse response(Map<String,Object> p) { return new ParticipantResponse(s(p,"id"),s(p,"user_id"),s(p,"status"),s(p,"invited_by_user_id"),instant(p,"invited_at"),instant(p,"joined_at"),instant(p,"ended_at"),instant(p,"created_at"),instant(p,"updated_at")); }
  private static String s(Map<String,Object> row,String key) { Object v=row.get(key); return v==null?null:v.toString(); } private static Instant instant(Map<String,Object> row,String key) { Object v=row.get(key); return v==null?null:((Timestamp)v).toInstant(); }
  public record InvitationRequest(@NotBlank @Size(max=36) String userId) {} public record ParticipantResponse(String id,String userId,String status,String invitedByUserId,Instant invitedAt,Instant joinedAt,Instant endedAt,Instant createdAt,Instant updatedAt) {}
}
