package org.animallink.incident.api;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import org.animallink.incident.infrastructure.MinioIncidentMediaFormalizer;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api/v1")
public class EventController {
  private final JdbcTemplate jdbc; private final RestClient identity; private final RestClient animal; private final RestClient intelligence; private final MinioIncidentMediaFormalizer media; private final HttpServletRequest request;
  public EventController(JdbcTemplate jdbc, @Qualifier("identityRestClient") RestClient identityRestClient, @Qualifier("animalRestClient") RestClient animalRestClient, @Qualifier("intelligenceRestClient") RestClient intelligenceRestClient, MinioIncidentMediaFormalizer media, HttpServletRequest request){this.jdbc=jdbc;this.identity=identityRestClient;this.animal=animalRestClient;this.intelligence=intelligenceRestClient;this.media=media;this.request=request;}

  @PostMapping("/event-drafts") @Transactional public DraftResponse createDraft(@Valid @RequestBody DraftRequest r){
    User u=user(); membership(u.id,r.campusId); validateAnimal(r.campusId,r.animalId); validateProvenance(u.id,r); String id=UUID.randomUUID().toString(); Instant n=Instant.now();
    jdbc.update("INSERT INTO event_draft (id,user_id,campus_id,animal_id,description,abnormality_summary,occurred_at,public_location_description,exact_location_description,latitude,longitude,source_ai_task_id,source_matching_record_id,source_post_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,u.id,r.campusId,r.animalId,r.description,blank(r.abnormalitySummary),Timestamp.from(r.occurredAt),r.publicLocationDescription,blank(r.exactLocationDescription),r.latitude,r.longitude,blank(r.sourceAiTaskId),blank(r.sourceMatchingRecordId),blank(r.sourcePostId),Timestamp.from(n),Timestamp.from(n)); saveDraftMedia(id,r.media(),n); return draftResponse(one("SELECT * FROM event_draft WHERE id=?",id),id);
  }
  @PatchMapping("/event-drafts/{id}") @Transactional public DraftResponse patchDraft(@PathVariable("id") String id,@Valid@RequestBody DraftRequest r){
    User u=user();Map<String,Object>d=one("SELECT * FROM event_draft WHERE id=? FOR UPDATE",id);if(!u.id.equals(s(d,"user_id")))throw new NotFound("草稿不存在");if(s(d,"final_event_id")!=null)throw new Conflict("已提交的草稿不能修改");membership(u.id,s(d,"campus_id"));validateAnimal(s(d,"campus_id"),r.animalId);validateProvenance(u.id,r);jdbc.update("UPDATE event_draft SET animal_id=?,description=?,abnormality_summary=?,occurred_at=?,public_location_description=?,exact_location_description=?,latitude=?,longitude=?,source_ai_task_id=?,source_matching_record_id=?,source_post_id=?,updated_at=? WHERE id=?",r.animalId,r.description,blank(r.abnormalitySummary),Timestamp.from(r.occurredAt),r.publicLocationDescription,blank(r.exactLocationDescription),r.latitude,r.longitude,blank(r.sourceAiTaskId),blank(r.sourceMatchingRecordId),blank(r.sourcePostId),Timestamp.from(Instant.now()),id);if(r.media()!=null){jdbc.update("DELETE FROM event_draft_media WHERE event_draft_id=?",id);saveDraftMedia(id,r.media(),Instant.now());}return draftResponse(one("SELECT * FROM event_draft WHERE id=?",id),id);
  }
  @PostMapping("/event-drafts/{id}/submit") @Transactional public EventResponse submit(@PathVariable("id") String id){
    User u=user(); Map<String,Object> d=one("SELECT * FROM event_draft WHERE id=? FOR UPDATE",id); if(!u.id.equals(s(d,"user_id"))) throw new Forbidden("只能提交本人草稿");
    String finalId=s(d,"final_event_id"); if(finalId!=null)return event(finalId,false);
    membership(u.id,s(d,"campus_id")); validateAnimal(s(d,"campus_id"),s(d,"animal_id")); String eid=UUID.randomUUID().toString(); Instant n=Instant.now();
    jdbc.update("INSERT INTO event (id,source_draft_id,reporter_user_id,campus_id,animal_id,description,abnormality_summary,occurred_at,reported_at,public_location_description,exact_location_description,latitude,longitude,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",eid,id,u.id,s(d,"campus_id"),s(d,"animal_id"),s(d,"description"),s(d,"abnormality_summary"),d.get("occurred_at"),Timestamp.from(n),s(d,"public_location_description"),s(d,"exact_location_description"),d.get("latitude"),d.get("longitude"),"REPORTED",Timestamp.from(n),Timestamp.from(n));
    copyDraftMedia(u.id(),id,eid); jdbc.update("UPDATE event_draft SET finalized_at=?,final_event_id=?,updated_at=? WHERE id=?",Timestamp.from(n),eid,Timestamp.from(n),id); return event(eid,true);
  }
  @GetMapping("/events") public PageResponse list(@RequestParam("campusId") String campusId,@RequestParam(value="status",required=false) String status,@RequestParam(value="animalId",required=false) String animalId,@RequestParam(value="page",defaultValue="0")@Min(0) int page,@RequestParam(value="size",defaultValue="20")@Min(1)@Max(100) int size){
    String sql="SELECT id,campus_id,animal_id,description,abnormality_summary,occurred_at,reported_at,public_location_description,status,duplicate_of_event_id FROM event WHERE campus_id=?"; List<Object>a=new ArrayList<>(List.of(campusId)); if(status!=null){sql+=" AND status=?";a.add(status);}else sql+=" AND status IN ('REPORTED','VERIFIED')";if(animalId!=null){sql+=" AND animal_id=?";a.add(animalId);} long total=jdbc.queryForObject("SELECT COUNT(*) FROM ("+sql+") x",Long.class,a.toArray()); sql+=" ORDER BY reported_at DESC,id DESC LIMIT ? OFFSET ?";a.add(size);a.add(page*size);List<Map<String,Object>> rows=jdbc.queryForList(sql,a.toArray());return new PageResponse(rows.stream().map(x->new EventResponse(s(x,"id"),s(x,"campus_id"),s(x,"animal_id"),s(x,"description"),s(x,"abnormality_summary"),instant(x,"occurred_at"),instant(x,"reported_at"),s(x,"public_location_description"),s(x,"status"),s(x,"duplicate_of_event_id"),List.<EvidenceResponse>of(),List.of(),null,null,null)).toList(),page,size,total);
  }
  @GetMapping("/events/{id}") public EventResponse detail(@PathVariable("id") String id){return event(id,false);}
  @GetMapping("/event-drafts/{id}") public DraftResponse draft(@PathVariable("id") String id){User u=user();Map<String,Object>d=one("SELECT * FROM event_draft WHERE id=?",id);if(!u.id.equals(s(d,"user_id")))throw new NotFound("草稿不存在");return draftResponse(d,id);}
  @GetMapping("/events/{id}/evidence") public EvidencePageResponse evidencePage(@PathVariable("id") String id,@RequestParam(value="page",defaultValue="0")@Min(0)int page,@RequestParam(value="size",defaultValue="20")@Min(1)@Max(100)int size){Map<String,Object> event=eventOne(id);User viewer;try{viewer=user();}catch(RuntimeException ex){viewer=null;}final User current=viewer;long total=jdbc.queryForObject("SELECT COUNT(*) FROM evidence WHERE event_id=?",Long.class,id);List<EvidenceResponse> items=jdbc.queryForList("SELECT * FROM evidence WHERE event_id=? ORDER BY created_at,id LIMIT ? OFFSET ?",id,size,page*size).stream().map(row->evidenceResponse(row,event,current)).toList();return new EvidencePageResponse(items,page,size,total);}
  @PostMapping("/events/{id}/evidence") @Transactional public EvidenceResponse evidence(@PathVariable("id") String id,@Valid @RequestBody EvidenceRequest r){User u=user();Map<String,Object>e=eventOneForUpdate(id);membership(u.id,s(e,"campus_id"));if(!Set.of("REPORTED","VERIFIED").contains(s(e,"status")))throw new Conflict("当前 Event 不接受 Evidence");String eid=UUID.randomUUID().toString();Instant n=Instant.now();jdbc.update("INSERT INTO evidence (id,event_id,submitter_user_id,description,occurred_at,public_location_description,exact_location_description,latitude,longitude,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",eid,id,u.id,r.description,Timestamp.from(r.occurredAt),blank(r.publicLocationDescription),blank(r.exactLocationDescription),r.latitude,r.longitude,Timestamp.from(n));copyEvidenceMedia(u.id(),eid,r.media());return new EvidenceResponse(eid,id,r.description,r.occurredAt,r.publicLocationDescription,r.exactLocationDescription,r.latitude,r.longitude,n,List.of());}
  @PostMapping("/admin/events/{id}/verify") public EventResponse verify(@PathVariable("id") String id){return transition(id,"VERIFIED",null);}
  @PostMapping("/admin/events/{id}/reject") public EventResponse reject(@PathVariable("id") String id){return transition(id,"REJECTED",null);}
  @PostMapping("/admin/events/{id}/archive") public EventResponse archive(@PathVariable("id") String id){return transition(id,"ARCHIVED",null);}
  @PostMapping("/admin/events/{id}/mark-duplicate") public EventResponse duplicate(@PathVariable("id") String id,@Valid@RequestBody DuplicateRequest r){Map<String,Object> target=eventOne(r.canonicalEventId);Map<String,Object> src=eventOne(id);if(id.equals(r.canonicalEventId)||!s(src,"campus_id").equals(s(target,"campus_id")))throw new Conflict("重复目标必须是同 Campus 的另一 Event");return transition(id,"DUPLICATE",r.canonicalEventId);}
  @Transactional EventResponse transition(String id,String next,String duplicate){admin();Map<String,Object>e=eventOneForUpdate(id);String cur=s(e,"status");boolean ok=("VERIFIED".equals(next)&&"REPORTED".equals(cur))||("ARCHIVED".equals(next)&&"VERIFIED".equals(cur))||(("REJECTED".equals(next)||"DUPLICATE".equals(next))&&"REPORTED".equals(cur));if(!ok)throw new Conflict("当前 Event 状态不允许该治理操作");jdbc.update("UPDATE event SET status=?,duplicate_of_event_id=?,updated_at=? WHERE id=?",next,duplicate,Timestamp.from(Instant.now()),id);return event(id,false);}
  private EventResponse event(String id,boolean ignored){Map<String,Object>e=eventOne(id);User viewer;try{viewer=user();}catch(RuntimeException ex){viewer=null;}final User current=viewer;List<EvidenceResponse> evidence=jdbc.queryForList("SELECT * FROM evidence WHERE event_id=? ORDER BY created_at,id LIMIT 20",id).stream().map(row->evidenceResponse(row,e,current)).toList();boolean exact=current!=null&&(current.id.equals(s(e,"reporter_user_id"))||"GOVERNANCE_ADMIN".equals(current.role));return new EventResponse(id,s(e,"campus_id"),s(e,"animal_id"),s(e,"description"),s(e,"abnormality_summary"),instant(e,"occurred_at"),instant(e,"reported_at"),s(e,"public_location_description"),s(e,"status"),s(e,"duplicate_of_event_id"),evidence,eventMedia(id),exact?s(e,"exact_location_description"):null,exact?number(e,"latitude"):null,exact?number(e,"longitude"):null);
  }
  private void membership(String user,String campus){try{Map<?,?>m=identity.get().uri("/internal/v1/users/{u}/campus-memberships/{c}",user,campus).retrieve().body(Map.class);if(m==null||!Boolean.TRUE.equals(m.get("exists"))||!"ACTIVE".equals(m.get("status")))throw new Forbidden("需要目标 Campus 的有效成员身份");}catch(RestClientResponseException x){throw new Dependency("identity-service 暂不可用");}}
  private void validateAnimal(String campus,String animalId){if(animalId==null)return;try{Map<?,?>a=animal.get().uri("/internal/v1/incident-facts/animals/{id}",animalId).header("X-Internal-Service","incident-service").retrieve().body(Map.class);if(a==null||!campus.equals(a.get("campusId")))throw new Conflict("Animal 必须属于同一 Campus");if(!"ACTIVE".equals(a.get("identityStatus")))throw new Conflict("Animal 未处于 ACTIVE 状态");}catch(RestClientResponseException x){throw new Dependency("animal-service 暂不可用，拒绝确认 Animal");}}
  private User user(){try{var spec=identity.get().uri("/api/v1/users/me");String h=request.getHeader("X-User-Id");if(h!=null)spec=spec.header("X-User-Id",h);Map<?,?>u=spec.retrieve().body(Map.class);if(u==null)throw new Unauthorized("需要登录");return new User((String)u.get("id"),(String)u.get("systemRole"));}catch(RestClientResponseException x){throw new Unauthorized("需要登录");}}
  private void admin(){if(!"GOVERNANCE_ADMIN".equals(user().role))throw new Forbidden("需要治理管理员权限");}private DraftResponse draftResponse(Map<String,Object>d,String id){return new DraftResponse(id,s(d,"campus_id"),s(d,"animal_id"),s(d,"description"),s(d,"abnormality_summary"),instant(d,"occurred_at"),s(d,"public_location_description"),s(d,"exact_location_description"),s(d,"final_event_id"),instant(d,"finalized_at"),instant(d,"created_at"),draftMedia(id));}
  private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new NotFound("资源不存在"));}private Map<String,Object> eventOne(String id){return jdbc.queryForList("SELECT * FROM event WHERE id=?",id).stream().findFirst().orElseThrow(()->new NotFound("Event 不存在"));}private Map<String,Object> eventOneForUpdate(String id){return jdbc.queryForList("SELECT * FROM event WHERE id=? FOR UPDATE",id).stream().findFirst().orElseThrow(()->new NotFound("Event 不存在"));}private static String s(Map<?,?>m,String k){Object v=m.get(k);return v==null?null:v.toString();}private static Double number(Map<?,?>m,String k){Object v=m.get(k);return v==null?null:((Number)v).doubleValue();}private static String blank(String v){return v==null||v.isBlank()?null:v;}private static Instant instant(Map<?,?>m,String k){Object v=m.get(k);return v instanceof Timestamp t?t.toInstant():(Instant)v;}
  record User(String id,String role){} public record DraftRequest(@NotBlank@Size(max=36)String campusId,@Size(max=36)String animalId,@NotBlank@Size(max=2000)String description,@Size(max=1000)String abnormalitySummary,@NotNull Instant occurredAt,@NotBlank@Size(max=500)String publicLocationDescription,@Size(max=1000)String exactLocationDescription,Double latitude,Double longitude,@Size(max=36)String sourceAiTaskId,@Size(max=36)String sourceMatchingRecordId,@Size(max=36)String sourcePostId,List<MediaInput> media){} public record DraftResponse(String id,String campusId,String animalId,String description,String abnormalitySummary,Instant occurredAt,String publicLocationDescription,String exactLocationDescription,String finalEventId,Instant finalizedAt,Instant createdAt,List<MediaSummary> media){} public record EvidenceRequest(@NotBlank@Size(max=2000)String description,@NotNull Instant occurredAt,@Size(max=500)String publicLocationDescription,@Size(max=1000)String exactLocationDescription,Double latitude,Double longitude,List<MediaInput> media){} public record EvidenceResponse(String id,String eventId,String description,Instant occurredAt,String publicLocationDescription,String exactLocationDescription,Double latitude,Double longitude,Instant createdAt,List<MediaSummary> media){} public record DuplicateRequest(@NotBlank@Size(max=36)String canonicalEventId){} public record EventResponse(String id,String campusId,String animalId,String description,String abnormalitySummary,Instant occurredAt,Instant reportedAt,String publicLocationDescription,String status,String duplicateOfEventId,List<EvidenceResponse> evidence,List<MediaSummary> media,String exactLocationDescription,Double latitude,Double longitude){} public record MediaSummary(String mediaId,String contentType,long sizeBytes,int sortOrder,String readUrl){} public record PageResponse(List<EventResponse> items,int page,int size,long total){} public record EvidencePageResponse(List<EvidenceResponse> items,int page,int size,long total){}
  static class NotFound extends RuntimeException{NotFound(String x){super(x);}} static class Forbidden extends RuntimeException{Forbidden(String x){super(x);}} static class Unauthorized extends RuntimeException{Unauthorized(String x){super(x);}} static class Conflict extends RuntimeException{Conflict(String x){super(x);}} static class Dependency extends RuntimeException{Dependency(String x){super(x);}}
  private void validateProvenance(String userId,DraftRequest r){try{if(r.sourceAiTaskId!=null&&!r.sourceAiTaskId.isBlank()){Map<?,?>f=intelligence.get().uri("/internal/v1/incident-facts/ai-tasks/{id}",r.sourceAiTaskId).header("X-Internal-Service","incident-service").retrieve().body(Map.class);if(f==null||!userId.equals(f.get("ownerUserId"))||!r.campusId.equals(f.get("campusId"))||!"SUCCEEDED".equals(f.get("status"))||!Boolean.TRUE.equals(f.get("confirmed")))throw new Conflict("AI 来源无效");}if(r.sourceMatchingRecordId!=null&&!r.sourceMatchingRecordId.isBlank()){Map<?,?>f=intelligence.get().uri("/internal/v1/incident-facts/matches/{id}",r.sourceMatchingRecordId).header("X-Internal-Service","incident-service").retrieve().body(Map.class);if(f==null||!userId.equals(f.get("ownerUserId"))||!r.campusId.equals(f.get("campusId"))||(r.sourceAiTaskId!=null&&!r.sourceAiTaskId.equals(f.get("aiTaskId"))))throw new Conflict("Matching 来源无效");}if(r.sourcePostId!=null&&!r.sourcePostId.isBlank()){Map<?,?>f=animal.get().uri("/internal/v1/incident-facts/posts/{id}",r.sourcePostId).header("X-Internal-Service","incident-service").retrieve().body(Map.class);if(f==null||!userId.equals(f.get("authorUserId"))||!r.campusId.equals(f.get("campusId"))||!"ACTIVE".equals(f.get("status")))throw new Conflict("Post 来源无效");}}catch(RestClientResponseException e){throw new Dependency("来源服务暂不可用，拒绝保存草稿");}}
  public record MediaInput(String temporaryObjectKey,String contentType,long sizeBytes,int sortOrder){} private void saveDraftMedia(String draftId,List<MediaInput> values,Instant now){if(values==null)return;for(MediaInput v:values){jdbc.update("INSERT INTO event_draft_media (id,event_draft_id,temporary_object_key,content_type,size_bytes,sort_order,created_at) VALUES (?,?,?,?,?,?,?)",UUID.randomUUID().toString(),draftId,v.temporaryObjectKey(),v.contentType(),v.sizeBytes(),v.sortOrder(),Timestamp.from(now));}}  private void copyEvidenceMedia(String userId,String evidenceId,List<MediaInput> values){if(values==null)return;List<MinioIncidentMediaFormalizer.Input> in=values.stream().map(x->new MinioIncidentMediaFormalizer.Input(x.temporaryObjectKey(),x.contentType(),x.sizeBytes(),x.sortOrder())).toList();try{for(var m:media.formalize(userId,evidenceId,"evidence",in)){jdbc.update("INSERT INTO evidence_media (id,evidence_id,object_key,content_type,size_bytes,sort_order,created_at) VALUES (?,?,?,?,?,?,?)",m.id(),evidenceId,m.key(),m.contentType(),m.size(),m.sortOrder(),Timestamp.from(Instant.now()));}}catch(IllegalStateException ex){throw new Dependency("MinIO 媒体正式化失败");}}
  private void copyDraftMedia(String userId,String draftId,String eventId){List<Map<String,Object>> rows=jdbc.queryForList("SELECT temporary_object_key,content_type,size_bytes,sort_order FROM event_draft_media WHERE event_draft_id=? ORDER BY sort_order,id",draftId);List<MinioIncidentMediaFormalizer.Input> in=rows.stream().map(x->new MinioIncidentMediaFormalizer.Input(s(x,"temporary_object_key"),s(x,"content_type"),((Number)x.get("size_bytes")).longValue(),((Number)x.get("sort_order")).intValue())).toList();for(var m:media.formalize(userId,eventId,"events",in)){jdbc.update("INSERT INTO event_media (id,event_id,object_key,content_type,size_bytes,sort_order,created_at) VALUES (?,?,?,?,?,?,?)",m.id(),eventId,m.key(),m.contentType(),m.size(),m.sortOrder(),Timestamp.from(Instant.now()));}}
  private EvidenceResponse evidenceResponse(Map<String,Object> row,Map<String,Object> event,User viewer){String evidenceId=s(row,"id");boolean exact=viewer!=null&&(viewer.id.equals(s(row,"submitter_user_id"))||viewer.id.equals(s(event,"reporter_user_id"))||"GOVERNANCE_ADMIN".equals(viewer.role));return new EvidenceResponse(evidenceId,s(row,"event_id"),s(row,"description"),instant(row,"occurred_at"),s(row,"public_location_description"),exact?s(row,"exact_location_description"):null,exact?number(row,"latitude"):null,exact?number(row,"longitude"):null,instant(row,"created_at"),evidenceMedia(evidenceId));}
  private List<MediaSummary> draftMedia(String draftId){return jdbc.queryForList("SELECT id,temporary_object_key,content_type,size_bytes,sort_order FROM event_draft_media WHERE event_draft_id=? ORDER BY sort_order,id",draftId).stream().map(row->mediaSummary(row,"temporary_object_key")).toList();}
  private List<MediaSummary> eventMedia(String eventId){return jdbc.queryForList("SELECT id,object_key,content_type,size_bytes,sort_order FROM event_media WHERE event_id=? ORDER BY sort_order,id",eventId).stream().map(row->mediaSummary(row,"object_key")).toList();}
  private List<MediaSummary> evidenceMedia(String evidenceId){return jdbc.queryForList("SELECT id,object_key,content_type,size_bytes,sort_order FROM evidence_media WHERE evidence_id=? ORDER BY sort_order,id",evidenceId).stream().map(row->mediaSummary(row,"object_key")).toList();}
  private MediaSummary mediaSummary(Map<String,Object> row,String objectKeyColumn){return new MediaSummary(s(row,"id"),s(row,"content_type"),((Number)row.get("size_bytes")).longValue(),((Number)row.get("sort_order")).intValue(),media.presignedReadUrl(s(row,objectKeyColumn)));}
}
