package org.animallink.incident.api;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api/v1")
public class EventController {
  private final JdbcTemplate jdbc; private final RestClient identity; private final RestClient animal; private final HttpServletRequest request;
  public EventController(JdbcTemplate jdbc, RestClient identityRestClient, RestClient animalRestClient, HttpServletRequest request){this.jdbc=jdbc;this.identity=identityRestClient;this.animal=animalRestClient;this.request=request;}

  @PostMapping("/event-drafts") @Transactional public DraftResponse createDraft(@Valid @RequestBody DraftRequest r){
    User u=user(); membership(u.id,r.campusId); validateAnimal(r.campusId,r.animalId); String id=UUID.randomUUID().toString(); Instant n=Instant.now();
    jdbc.update("INSERT INTO event_draft (id,user_id,campus_id,animal_id,description,abnormality_summary,occurred_at,public_location_description,exact_location_description,latitude,longitude,source_ai_task_id,source_matching_record_id,source_post_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,u.id,r.campusId,r.animalId,r.description,blank(r.abnormalitySummary),Timestamp.from(r.occurredAt),r.publicLocationDescription,blank(r.exactLocationDescription),r.latitude,r.longitude,blank(r.sourceAiTaskId),blank(r.sourceMatchingRecordId),blank(r.sourcePostId),Timestamp.from(n),Timestamp.from(n)); return new DraftResponse(id,null,null,n);
  }
  @PostMapping("/event-drafts/{id}/submit") @Transactional public EventResponse submit(@PathVariable String id){
    User u=user(); Map<String,Object> d=one("SELECT * FROM event_draft WHERE id=? FOR UPDATE",id); if(!u.id.equals(s(d,"user_id"))) throw new Forbidden("只能提交本人草稿");
    String finalId=s(d,"final_event_id"); if(finalId!=null)return event(finalId,false);
    membership(u.id,s(d,"campus_id")); validateAnimal(s(d,"campus_id"),s(d,"animal_id")); String eid=UUID.randomUUID().toString(); Instant n=Instant.now();
    jdbc.update("INSERT INTO event (id,source_draft_id,reporter_user_id,campus_id,animal_id,description,abnormality_summary,occurred_at,reported_at,public_location_description,exact_location_description,latitude,longitude,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",eid,id,u.id,s(d,"campus_id"),s(d,"animal_id"),s(d,"description"),s(d,"abnormality_summary"),d.get("occurred_at"),Timestamp.from(n),s(d,"public_location_description"),s(d,"exact_location_description"),d.get("latitude"),d.get("longitude"),"REPORTED",Timestamp.from(n),Timestamp.from(n));
    jdbc.update("UPDATE event_draft SET finalized_at=?,final_event_id=?,updated_at=? WHERE id=?",Timestamp.from(n),eid,Timestamp.from(n),id); return event(eid,true);
  }
  @GetMapping("/events") public PageResponse list(@RequestParam String campusId,@RequestParam(required=false) String status,@RequestParam(required=false) String animalId,@RequestParam(defaultValue="0")@Min(0) int page,@RequestParam(defaultValue="20")@Min(1)@Max(100) int size){
    String sql="SELECT id FROM event WHERE campus_id=?"; List<Object>a=new ArrayList<>(List.of(campusId)); if(status!=null){sql+=" AND status=?";a.add(status);}if(animalId!=null){sql+=" AND animal_id=?";a.add(animalId);} long total=jdbc.queryForObject("SELECT COUNT(*) FROM ("+sql+") x",Long.class,a.toArray()); sql+=" ORDER BY reported_at DESC,id DESC LIMIT ? OFFSET ?";a.add(size);a.add(page*size);return new PageResponse(jdbc.queryForList(sql,a.toArray()).stream().map(x->event(s(x,"id"),false)).toList(),page,size,total);
  }
  @GetMapping("/events/{id}") public EventResponse detail(@PathVariable String id){return event(id,false);}
  @GetMapping("/event-drafts/{id}") public DraftResponse draft(@PathVariable String id){User u=user();Map<String,Object>d=one("SELECT * FROM event_draft WHERE id=?",id);if(!u.id.equals(s(d,"user_id")))throw new Forbidden("只能查看本人草稿");return new DraftResponse(id,s(d,"final_event_id"),instant(d,"finalized_at"),instant(d,"created_at"));}
  @PostMapping("/events/{id}/evidence") @Transactional public EvidenceResponse evidence(@PathVariable String id,@Valid @RequestBody EvidenceRequest r){User u=user();Map<String,Object>e=one("SELECT * FROM event WHERE id=? FOR UPDATE",id);membership(u.id,s(e,"campus_id"));if(!Set.of("REPORTED","VERIFIED").contains(s(e,"status")))throw new Conflict("当前 Event 不接受 Evidence");String eid=UUID.randomUUID().toString();Instant n=Instant.now();jdbc.update("INSERT INTO evidence (id,event_id,submitter_user_id,description,occurred_at,public_location_description,exact_location_description,latitude,longitude,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",eid,id,u.id,r.description,Timestamp.from(r.occurredAt),blank(r.publicLocationDescription),blank(r.exactLocationDescription),r.latitude,r.longitude,Timestamp.from(n));return new EvidenceResponse(eid,id,r.description,r.occurredAt,r.publicLocationDescription,n);}
  @PostMapping("/admin/events/{id}/verify") public EventResponse verify(@PathVariable String id){return transition(id,"VERIFIED",null);}
  @PostMapping("/admin/events/{id}/reject") public EventResponse reject(@PathVariable String id){return transition(id,"REJECTED",null);}
  @PostMapping("/admin/events/{id}/archive") public EventResponse archive(@PathVariable String id){return transition(id,"ARCHIVED",null);}
  @PostMapping("/admin/events/{id}/mark-duplicate") public EventResponse duplicate(@PathVariable String id,@Valid@RequestBody DuplicateRequest r){Map<String,Object> target=one("SELECT * FROM event WHERE id=?",r.canonicalEventId);Map<String,Object> src=one("SELECT * FROM event WHERE id=?",id);if(id.equals(r.canonicalEventId)||!s(src,"campus_id").equals(s(target,"campus_id")))throw new Conflict("重复目标必须是同 Campus 的另一 Event");return transition(id,"DUPLICATE",r.canonicalEventId);}
  @Transactional EventResponse transition(String id,String next,String duplicate){admin();Map<String,Object>e=one("SELECT * FROM event WHERE id=? FOR UPDATE",id);String cur=s(e,"status");if(!("REPORTED".equals(cur)||"VERIFIED".equals(cur)))throw new Conflict("当前 Event 状态不允许该治理操作");jdbc.update("UPDATE event SET status=?,duplicate_of_event_id=?,updated_at=? WHERE id=?",next,duplicate,Timestamp.from(Instant.now()),id);return event(id,false);}
  private EventResponse event(String id,boolean reporterExact){Map<String,Object>e=one("SELECT * FROM event WHERE id=?",id);List<EvidenceResponse> evidence=jdbc.queryForList("SELECT * FROM evidence WHERE event_id=? ORDER BY created_at,id",id).stream().map(x->new EvidenceResponse(s(x,"id"),id,s(x,"description"),instant(x,"occurred_at"),s(x,"public_location_description"),instant(x,"created_at"))).toList();return new EventResponse(id,s(e,"campus_id"),s(e,"animal_id"),s(e,"description"),s(e,"abnormality_summary"),instant(e,"occurred_at"),instant(e,"reported_at"),s(e,"public_location_description"),s(e,"status"),s(e,"duplicate_of_event_id"),evidence);
  }
  private void membership(String user,String campus){try{Map<?,?>m=identity.get().uri("/internal/v1/users/{u}/campus-memberships/{c}",user,campus).retrieve().body(Map.class);if(m==null||!Boolean.TRUE.equals(m.get("exists"))||!"ACTIVE".equals(m.get("status")))throw new Forbidden("需要目标 Campus 的有效成员身份");}catch(RestClientResponseException x){throw new Dependency("identity-service 暂不可用");}}
  private void validateAnimal(String campus,String animalId){if(animalId==null)return;try{Map<?,?>a=animal.get().uri("/api/v1/animals/{id}",animalId).retrieve().body(Map.class);if(a==null||!campus.equals(a.get("campusId")))throw new Conflict("Animal 必须属于同一 Campus 且处于有效状态");}catch(RestClientResponseException x){throw new Dependency("animal-service 暂不可用，拒绝确认 Animal");}}
  private User user(){try{var spec=identity.get().uri("/api/v1/users/me");String h=request.getHeader("X-User-Id");if(h!=null)spec=spec.header("X-User-Id",h);Map<?,?>u=spec.retrieve().body(Map.class);if(u==null)throw new Unauthorized("需要登录");return new User((String)u.get("id"),(String)u.get("systemRole"));}catch(RestClientResponseException x){throw new Unauthorized("需要登录");}}
  private void admin(){if(!"GOVERNANCE_ADMIN".equals(user().role))throw new Forbidden("需要治理管理员权限");}
  private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new NotFound("资源不存在"));}private static String s(Map<?,?>m,String k){Object v=m.get(k);return v==null?null:v.toString();}private static String blank(String v){return v==null||v.isBlank()?null:v;}private static Instant instant(Map<?,?>m,String k){Object v=m.get(k);return v instanceof Timestamp t?t.toInstant():(Instant)v;}
  record User(String id,String role){} public record DraftRequest(@NotBlank@Size(max=36)String campusId,@Size(max=36)String animalId,@NotBlank@Size(max=2000)String description,@Size(max=1000)String abnormalitySummary,@NotNull Instant occurredAt,@NotBlank@Size(max=500)String publicLocationDescription,@Size(max=1000)String exactLocationDescription,Double latitude,Double longitude,@Size(max=36)String sourceAiTaskId,@Size(max=36)String sourceMatchingRecordId,@Size(max=36)String sourcePostId){} public record DraftResponse(String id,String finalEventId,Instant finalizedAt,Instant createdAt){} public record EvidenceRequest(@NotBlank@Size(max=2000)String description,@NotNull Instant occurredAt,@Size(max=500)String publicLocationDescription,@Size(max=1000)String exactLocationDescription,Double latitude,Double longitude){} public record EvidenceResponse(String id,String eventId,String description,Instant occurredAt,String publicLocationDescription,Instant createdAt){} public record DuplicateRequest(@NotBlank@Size(max=36)String canonicalEventId){} public record EventResponse(String id,String campusId,String animalId,String description,String abnormalitySummary,Instant occurredAt,Instant reportedAt,String publicLocationDescription,String status,String duplicateOfEventId,List<EvidenceResponse> evidence){} public record PageResponse(List<EventResponse> items,int page,int size,long total){}
  static class NotFound extends RuntimeException{NotFound(String x){super(x);}} static class Forbidden extends RuntimeException{Forbidden(String x){super(x);}} static class Unauthorized extends RuntimeException{Unauthorized(String x){super(x);}} static class Conflict extends RuntimeException{Conflict(String x){super(x);}} static class Dependency extends RuntimeException{Dependency(String x){super(x);}}
}
