package org.animallink.incident.api;
import io.minio.*;import io.minio.errors.ErrorResponseException;import io.minio.http.Method;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.beans.factory.annotation.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestClient;import java.util.*;
@RestController @RequestMapping("/api/v1/incident-media") public class IncidentMediaController {
 private static final Logger log=LoggerFactory.getLogger(IncidentMediaController.class);
 private final MinioClient minio;private final String bucket;private final RestClient identity;private final HttpServletRequest request;
 public IncidentMediaController(MinioClient minio,@Value("${animallink.minio.bucket}")String bucket,@Qualifier("identityRestClient")RestClient identity,HttpServletRequest request){this.minio=minio;this.bucket=bucket;this.identity=identity;this.request=request;}
 @PostMapping("/upload-url") public UploadResponse upload(@Valid@RequestBody UploadRequest r){if(!(r.contentType.startsWith("image/")||r.contentType.startsWith("video/")))throw new IllegalArgumentException("仅允许 image/* 或 video/* 媒体");try{var call=identity.get().uri("/api/v1/users/me");String h=request.getHeader("X-User-Id");if(h!=null)call=call.header("X-User-Id",h);Map<?,?>u=call.retrieve().body(Map.class);if(u==null)throw new EventController.Unauthorized("需要登录");String uid=(String)u.get("id");Map<?,?>m=identity.get().uri("/internal/v1/users/{u}/campus-memberships/{c}",uid,r.campusId).retrieve().body(Map.class);if(m==null||!Boolean.TRUE.equals(m.get("exists"))||!"ACTIVE".equals(m.get("status")))throw new EventController.Forbidden("需要目标 Campus 的有效成员身份");String safe=r.fileName.replaceAll("[^A-Za-z0-9._-]","_");String key="incident-input/"+uid+"/"+UUID.randomUUID()+"-"+safe;String url;try{url=minio.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().method(Method.PUT).bucket(bucket).object(key).expiry(600).build());}catch(Exception e){logMinioFailure("getPresignedObjectUrl",e);throw new EventController.Dependency("MinIO 暂不可用，无法生成上传地址");}return new UploadResponse(key,url,600);}catch(EventController.Unauthorized|EventController.Forbidden|EventController.Dependency e){throw e;}catch(Exception e){throw new EventController.Dependency("MinIO 或身份服务暂不可用，无法生成上传地址");}}
 private void logMinioFailure(String operation,Exception exception){String code=null;Throwable cause=exception;while(cause!=null){if(cause instanceof ErrorResponseException error){code=error.errorResponse().code();break;}cause=cause.getCause();}log.warn("MinIO operation failed: operation={}, bucket={}, exceptionClass={}, s3ErrorCode={}",operation,bucket,exception.getClass().getName(),code);}
 public record UploadRequest(@NotBlank@Size(max=36)String campusId,@NotBlank@Size(max=128)String fileName,@NotBlank@Size(max=128)String contentType,@Min(1)@Max(10485760)long sizeBytes){} public record UploadResponse(String objectKey,String uploadUrl,int expiresInSeconds){}
}
