CREATE TABLE volunteer_membership (
  id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  campus_id CHAR(36) NOT NULL,
  status VARCHAR(32) NOT NULL,
  application_note VARCHAR(500) NULL,
  review_reason VARCHAR(500) NULL,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME(6) NULL,
  activated_at DATETIME(6) NULL,
  paused_at DATETIME(6) NULL,
  ended_at DATETIME(6) NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_volunteer_membership_user_campus (user_id, campus_id),
  KEY idx_volunteer_membership_user_status (user_id, status),
  KEY idx_volunteer_membership_campus_status (campus_id, status),
  KEY idx_volunteer_membership_status_created (status, created_at),
  CONSTRAINT fk_volunteer_membership_user FOREIGN KEY (user_id) REFERENCES `user` (id),
  CONSTRAINT fk_volunteer_membership_campus FOREIGN KEY (campus_id) REFERENCES campus (id),
  CONSTRAINT fk_volunteer_membership_reviewer FOREIGN KEY (reviewed_by) REFERENCES `user` (id),
  CONSTRAINT chk_volunteer_membership_status CHECK (status IN ('PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'REJECTED', 'EXITED', 'REVOKED'))
) ENGINE=InnoDB;
