package org.animallink.incident;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers
class CaseResultIntegrationTest {
  static final String CAMPUS="30000000-0000-0000-0000-000000000001",OWNER="30000000-0000-0000-0000-000000000011",TARGET="30000000-0000-0000-0000-000000000012",OTHER="30000000-0000-0000-0000-000000000013",ADMIN="30000000-0000-0000-0000-000000000015",REPORTER="30000000-0000-0000-0000-000000000014";
  static final Stub STUB=new Stub();
  @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_result_test").withUsername("test").withPassword("test");
  @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"a");r.add("animallink.minio.secret-key",()->"b");r.add("animallink.minio.bucket",()->"b");}
  @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
  @BeforeEach void clean(){STUB.memberships.clear();STUB.memberships.put(OWNER,"ACTIVE");STUB.memberships.put(TARGET,"ACTIVE");STUB.memberships.put(OTHER,"ACTIVE");STUB.unavailable=false;jdbc.update("DELETE FROM case_action_media");jdbc.update("DELETE FROM case_action");jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}
  @AfterAll static void stop(){STUB.stop();}
  @Test void ownerContinueObservationAppendsHistoryAndKeepsCaseActive() throws Exception {String c=seed("continue");result(c,OWNER,"CONTINUE_OBSERVATION","watch").andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("ACTIVE")).andExpect(jsonPath("$.outcome").value("CONTINUE_OBSERVATION"));assertEquals("CONTINUE_OBSERVATION",value(c,"result_code"));assertEquals(1,count("case_action"));assertEquals("CONTINUE_OBSERVATION",jdbc.queryForObject("SELECT result_code FROM case_action WHERE case_id=?",String.class,c));}
  @Test void collaboratorResolvedAndOwnerClosePreservesResult() throws Exception {String c=seed("resolved");participant(c,TARGET,"ACTIVE");result(c,TARGET,"RESOLVED","done").andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("RESOLVED"));mvc.perform(post("/api/v1/cases/{id}/close",c).header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("CLOSED")).andExpect(jsonPath("$.resultCode").value("RESOLVED")).andExpect(jsonPath("$.closedAt").isNotEmpty());}
  @Test void terminalOutcomesAndAccessAreEnforced() throws Exception {String unresolved=seed("unresolved");result(unresolved,OWNER,"UNRESOLVED","no").andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("CLOSED_UNRESOLVED"));String cancelled=seed("cancelled");participant(cancelled,TARGET,"ACTIVE");result(cancelled,TARGET,"CANCELLED","cancel").andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("CANCELLED"));String denied=seed("denied");result(denied,OTHER,"RESOLVED","x").andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_RESULT_ACCESS_REQUIRED"));}
  @Test void inactiveIdentityAndTerminalCaseHaveNoMutation() throws Exception {String c=seed("paused");STUB.memberships.put(OWNER,"PAUSED");result(c,OWNER,"RESOLVED","x").andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));assertEquals(0,count("case_action"));STUB.memberships.put(OWNER,"ACTIVE");result(c,OWNER,"RESOLVED","x").andExpect(status().isOk());result(c,OWNER,"CONTINUE_OBSERVATION","late").andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_RESULT_STATE_CONFLICT"));assertEquals(1,count("case_action"));}
  @Test void participantStatesValidationIdentityAndIsolationAreEnforced() throws Exception {for(String state:java.util.List.of("INVITED","DECLINED","LEFT","REMOVED")){String c=seed("terminal-"+state);participant(c,TARGET,state);result(c,TARGET,"RESOLVED","x").andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_RESULT_ACCESS_REQUIRED"));}String revoked=seed("revoked");participant(revoked,TARGET,"ACTIVE");STUB.memberships.put(TARGET,"REVOKED");result(revoked,TARGET,"RESOLVED","x").andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));assertEquals(0,count("case_action"));STUB.memberships.put(TARGET,"ACTIVE");String down=seed("down");STUB.unavailable=true;try{result(down,OWNER,"RESOLVED","x").andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));}finally{STUB.unavailable=false;}result("missing",OWNER,"RESOLVED","x").andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("CASE_NOT_FOUND"));String validation=seed("validation");mvc.perform(post("/api/v1/cases/{id}/result",validation).header("X-User-Id",OWNER).contentType("application/json").content("{\"outcome\":\"BAD\",\"summary\":\" \"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));}
  @Test void continueThenResolvedPreservesTwoActionsAndTerminalBlocksActions() throws Exception {String c=seed("history");result(c,OWNER,"CONTINUE_OBSERVATION","observe").andExpect(status().isOk());mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",OWNER).contentType("application/json").content("{\"description\":\"ordinary\",\"occurredAt\":\"2026-10-03T10:00:00Z\"}")).andExpect(status().isOk());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM case_action WHERE case_id=? AND result_code IS NULL",Integer.class,c));result(c,OWNER,"RESOLVED","resolved").andExpect(status().isOk());assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM case_action WHERE case_id=? AND result_code IS NOT NULL",Integer.class,c));mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",OWNER).contentType("application/json").content("{\"description\":\"late\",\"occurredAt\":\"2026-10-03T10:00:00Z\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_NOT_ACTIVE"));assertEquals("VERIFIED",jdbc.queryForObject("SELECT status FROM event WHERE id=?",String.class,"e-history"));assertEquals(0,count("evidence"));}
  @Test void closeAuthorizationAndStateRulesAreEnforced() throws Exception {String c=seed("close-auth");result(c,OWNER,"RESOLVED","done").andExpect(status().isOk());participant(c,TARGET,"ACTIVE");mvc.perform(post("/api/v1/cases/{id}/close",c).header("X-User-Id",TARGET)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_CLOSE_OWNER_REQUIRED"));mvc.perform(post("/api/v1/cases/{id}/close",c).header("X-User-Id",ADMIN)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_CLOSE_OWNER_REQUIRED"));STUB.memberships.put(OWNER,"PAUSED");mvc.perform(post("/api/v1/cases/{id}/close",c).header("X-User-Id",OWNER)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));STUB.memberships.put(OWNER,"ACTIVE");mvc.perform(post("/api/v1/cases/{id}/close",c).header("X-User-Id",OWNER)).andExpect(status().isOk());String active=seed("active-close");mvc.perform(post("/api/v1/cases/{id}/close",active).header("X-User-Id",OWNER)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_NOT_RESOLVED"));}
  private org.springframework.test.web.servlet.ResultActions result(String c,String u,String outcome,String summary)throws Exception{return mvc.perform(post("/api/v1/cases/{id}/result",c).header("X-User-Id",u).contentType("application/json").content("{\"outcome\":\""+outcome+"\",\"summary\":\""+summary+"\"}"));}
  private String seed(String x){Timestamp n=Timestamp.from(Instant.now());String e="e-"+x,d="d-"+x,c="c-"+x;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,REPORTER,CAMPUS,"d",n,"p",n,n);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",e,d,REPORTER,CAMPUS,"e",n,n,"p","VERIFIED",n,n);jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",c,e,CAMPUS,OWNER,"ACTIVE","CLAIMED",n,n,n);return c;}
  private void participant(String c,String u,String status){Timestamp n=Timestamp.from(Instant.now());if("ACTIVE".equals(status))jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,status,OWNER,n,n,n,n);else if("INVITED".equals(status))jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,status,OWNER,n,n,n);else jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,ended_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,status,OWNER,n,n,n,n,n);}
  private int count(String table){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class);} private String value(String c,String column){return jdbc.queryForObject("SELECT "+column+" FROM animal_case WHERE id=?",String.class,c);}
  static class Stub {final HttpServer server;final Map<String,String> memberships=new ConcurrentHashMap<>();volatile boolean unavailable;Stub(){try{server=HttpServer.create(new InetSocketAddress(0),0);server.createContext("/",this::handle);server.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+server.getAddress().getPort();}void stop(){server.stop(0);}void handle(HttpExchange e)throws IOException{String path=e.getRequestURI().getPath(),header=e.getRequestHeaders().getFirst("X-User-Id");if(unavailable&&path.contains("volunteer-membership")){e.sendResponseHeaders(503,-1);e.close();return;}String[] parts=path.split("/");String subject=parts.length>4?parts[4]:header;String json=path.contains("volunteer-membership")?("ACTIVE".equals(memberships.get(subject))?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"exists\":true,\"active\":false,\"status\":\"PAUSED\"}"):"{\"id\":\""+header+"\",\"systemRole\":\""+(ADMIN.equals(header)?"GOVERNANCE_ADMIN":"USER")+"\"}";byte[] body=json.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,body.length);e.getResponseBody().write(body);e.close();}}
}
