package org.animallink.incident;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import static org.hamcrest.Matchers.nullValue;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers class CaseParticipantIntegrationTest {
  static final String CAMPUS="10000000-0000-0000-0000-000000000101", OTHER_CAMPUS="10000000-0000-0000-0000-000000000102", OWNER="00000000-0000-0000-0000-000000000201", TARGET="00000000-0000-0000-0000-000000000202", OTHER="00000000-0000-0000-0000-000000000203", REPORTER="00000000-0000-0000-0000-000000000204", ADMIN="00000000-0000-0000-0000-000000000999";
  static final Stub STUB=new Stub(); @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_participant_test").withUsername("test").withPassword("test");
  @DynamicPropertySource static void p(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"minioadmin");r.add("animallink.minio.secret-key",()->"minioadmin");r.add("animallink.minio.bucket",()->"animallink-incident");}
  @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired ObjectMapper mapper;
  @BeforeEach void clean(){STUB.memberships.clear();STUB.unavailable=false;active(OWNER,TARGET,OTHER,REPORTER,ADMIN);jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM evidence_media");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event_media");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}
  @AfterAll static void stop(){STUB.stop();}

  @Test void inviteRequiresActiveOwnerAndEligibleTargetAndPreventsDuplicateLifecycleRows()throws Exception{String c=caseId("active");invite(c,TARGET).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("INVITED")).andExpect(jsonPath("$.joinedAt").value(nullValue())).andExpect(jsonPath("$.endedAt").value(nullValue()));invite(c,TARGET).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_PARTICIPANT_EXISTS"));invite(c,OWNER).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CANNOT_INVITE_CASE_OWNER"));mvc.perform(post("/api/v1/cases/{id}/participants/invitations",c).header("X-User-Id",OTHER).contentType("application/json").content("{\"userId\":\""+TARGET+"\"}")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_OWNER_REQUIRED"));for(String state:List.of("PENDING_REVIEW","PAUSED","EXITED","REVOKED")){String id=caseId("target-"+state);STUB.memberships.put(TARGET,state);invite(id,TARGET).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));STUB.memberships.put(TARGET,"ACTIVE");}STUB.memberships.put(TARGET,"WRONG_CAMPUS");invite(caseId("wrong-campus"),TARGET).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));}
  @Test void inviteRejectsMissingAndInactiveCases()throws Exception{invite("missing",TARGET).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("CASE_NOT_FOUND"));String c=caseId("inactive");jdbc.update("UPDATE animal_case SET status='OPEN' WHERE id=?",c);invite(c,TARGET).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_NOT_ACTIVE"));}
  @Test void acceptDeclineLeaveAndRemoveUseConditionalLifecycleTransitions()throws Exception{String c=caseId("transitions");String first=inviteId(c,TARGET);mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,first).header("X-User-Id",OTHER)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_PARTICIPANT_TARGET_REQUIRED"));STUB.memberships.put(TARGET,"PAUSED");mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,first).header("X-User-Id",TARGET)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));STUB.memberships.put(TARGET,"ACTIVE");mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,first).header("X-User-Id",TARGET)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ACTIVE")).andExpect(jsonPath("$.joinedAt").isNotEmpty());mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,first).header("X-User-Id",TARGET)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_PARTICIPANT_STATE_CONFLICT"));STUB.memberships.put(TARGET,"REVOKED");mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/leave",c,first).header("X-User-Id",TARGET)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("LEFT")).andExpect(jsonPath("$.endedAt").isNotEmpty());String second=inviteId(c,OTHER);mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/decline",c,second).header("X-User-Id",OTHER)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DECLINED")).andExpect(jsonPath("$.endedAt").isNotEmpty());invite(c,OTHER).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_PARTICIPANT_EXISTS")); }
  @Test void ownerCanRemoveActiveParticipantAndListIsRestricted()throws Exception{String c=caseId("remove");String p=inviteId(c,TARGET);accept(c,p,TARGET);mvc.perform(get("/api/v1/cases/{id}/participants",c).header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$[0].userId").value(TARGET));mvc.perform(get("/api/v1/cases/{id}/participants",c).header("X-User-Id",TARGET)).andExpect(status().isOk());mvc.perform(get("/api/v1/cases/{id}/participants",c).header("X-User-Id",ADMIN)).andExpect(status().isOk());mvc.perform(get("/api/v1/cases/{id}/participants",c).header("X-User-Id",OTHER)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_PARTICIPANT_ACCESS_REQUIRED"));mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/remove",c,p).header("X-User-Id",OTHER)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_OWNER_REQUIRED"));mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/remove",c,p).header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("REMOVED")).andExpect(jsonPath("$.endedAt").isNotEmpty());}
  @Test void identityUnavailableForWritesDoesNotMutate()throws Exception{String c=caseId("unavailable");STUB.unavailable=true;invite(c,TARGET).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM case_participant WHERE case_id=?",Integer.class,c));STUB.unavailable=false;String p=inviteId(c,TARGET);STUB.unavailable=true;mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,p).header("X-User-Id",TARGET)).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));assertEquals("INVITED",jdbc.queryForObject("SELECT status FROM case_participant WHERE id=?",String.class,p));STUB.unavailable=false;accept(c,p,TARGET);STUB.unavailable=true;mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/remove",c,p).header("X-User-Id",OWNER)).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM case_participant WHERE id=?",String.class,p));}
  @Test void databaseConstraintsProtectParticipantRelation(){String c=caseId("constraints");Timestamp now=Timestamp.from(Instant.now());jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)","p1",c,TARGET,"INVITED",OWNER,now,now,now);assertThrows(RuntimeException.class,()->jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)","p2",c,TARGET,"INVITED",OWNER,now,now,now));assertThrows(RuntimeException.class,()->jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)","bad","missing",OTHER,"INVITED",OWNER,now,now,now));assertThrows(RuntimeException.class,()->jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)","bad-state",c,OTHER,"BROKEN",OWNER,now,now,now));}
  @Test void activeCollaboratorGetsPreciseLocationAndTerminalStatesDoNot()throws Exception{String c=caseId("location");jdbc.update("UPDATE event SET exact_location_description='exact',latitude=31.1,longitude=121.2 WHERE id='event-location'");Map<String,Object> eventMap=jdbc.queryForMap("SELECT * FROM event WHERE id=?","event-location");assertEquals("exact",eventMap.get("exact_location_description"));assertNotNull(eventMap.get("latitude"));assertNotNull(eventMap.get("longitude"));jdbc.update("INSERT INTO evidence(id,event_id,submitter_user_id,description,occurred_at,public_location_description,exact_location_description,latitude,longitude,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)","e-location","event-location",OTHER,"e",Timestamp.from(Instant.now()),"public","exact-e",31.2,121.3,Timestamp.from(Instant.now()));String p=inviteId(c,TARGET);accept(c,p,TARGET);Map<String,Object> participantRow=jdbc.queryForMap("SELECT c.id,c.event_id,c.owner_user_id,p.id AS participant_id,p.user_id,p.status,p.joined_at,p.ended_at FROM animal_case c LEFT JOIN case_participant p ON p.case_id=c.id WHERE c.event_id='event-location'");assertEquals("case-location",participantRow.get("id"));assertEquals("event-location",participantRow.get("event_id"));assertEquals(TARGET,participantRow.get("user_id"));assertEquals("ACTIVE",participantRow.get("status"));assertNotNull(participantRow.get("joined_at"));assertNull(participantRow.get("ended_at"));Map<String,Object> accessRow=jdbc.queryForMap("SELECT c.owner_user_id,EXISTS (SELECT 1 FROM case_participant p WHERE p.case_id=c.id AND p.user_id=? AND p.status='ACTIVE') AS active_participant FROM animal_case c WHERE c.event_id=?",TARGET,"event-location");Object activeParticipant=accessRow.get("active_participant");assertEquals(OWNER,accessRow.get("owner_user_id"));assertTrue(activeParticipant instanceof Number && ((Number)activeParticipant).intValue()==1,()->"active_participant="+activeParticipant+", type="+(activeParticipant==null?"null":activeParticipant.getClass().getName()));visible(TARGET,"event-location");visibleEvidence(TARGET,"event-location");hidden(OTHER,"event-location");visibleEvidence(OTHER,"event-location");mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/leave",c,p).header("X-User-Id",TARGET)).andExpect(status().isOk());hidden(TARGET,"event-location");hiddenEvidence(TARGET,"event-location");for(String viewer:List.of(OWNER,REPORTER,ADMIN))visible(viewer,"event-location");for(String viewer:List.of(OWNER,REPORTER,ADMIN))visibleEvidence(viewer,"event-location");}
  private void active(String...users){for(String u:users)STUB.memberships.put(u,"ACTIVE");} private String caseId(String suffix){Timestamp t=Timestamp.from(Instant.now());String event="event-"+suffix;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)","draft-"+suffix,REPORTER,CAMPUS,"d",t,"p",t,t);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",event,"draft-"+suffix,REPORTER,CAMPUS,"e",t,t,"p","VERIFIED",t,t);String id="case-"+suffix;jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",id,event,CAMPUS,OWNER,"ACTIVE","CLAIMED",t,t,t);return id;} private org.springframework.test.web.servlet.ResultActions invite(String c,String target)throws Exception{return mvc.perform(post("/api/v1/cases/{id}/participants/invitations",c).header("X-User-Id",OWNER).contentType("application/json").content("{\"userId\":\""+target+"\"}"));} private String inviteId(String c,String target)throws Exception{return mapper.readTree(invite(c,target).andExpect(status().isOk()).andReturn().getResponse().getContentAsString()).required("id").asText();} private void accept(String c,String p,String u)throws Exception{mvc.perform(post("/api/v1/cases/{caseId}/participants/{participantId}/accept",c,p).header("X-User-Id",u)).andExpect(status().isOk());} private void visible(String u,String event)throws Exception{mvc.perform(get("/api/v1/events/{id}",event).header("X-User-Id",u)).andExpect(jsonPath("$.exactLocationDescription").isNotEmpty());} private void hidden(String u,String event)throws Exception{mvc.perform(get("/api/v1/events/{id}",event).header("X-User-Id",u)).andExpect(jsonPath("$.exactLocationDescription").value(nullValue()));} private void visibleEvidence(String u,String event)throws Exception{mvc.perform(get("/api/v1/events/{id}/evidence",event).header("X-User-Id",u)).andExpect(jsonPath("$.items[0].exactLocationDescription").isNotEmpty());} private void hiddenEvidence(String u,String event)throws Exception{mvc.perform(get("/api/v1/events/{id}/evidence",event).header("X-User-Id",u)).andExpect(jsonPath("$.items[0].exactLocationDescription").value(nullValue()));}
  static class Stub { final HttpServer server;final Map<String,String> memberships=new ConcurrentHashMap<>();volatile boolean unavailable;Stub(){try{server=HttpServer.create(new InetSocketAddress(0),0);server.createContext("/",this::handle);server.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+server.getAddress().getPort();}void stop(){server.stop(0);}void handle(HttpExchange e)throws IOException{String path=e.getRequestURI().getPath(),user=e.getRequestHeaders().getFirst("X-User-Id");if(unavailable&&path.contains("volunteer-membership")){e.sendResponseHeaders(503,-1);e.close();return;}String[] s=path.split("/");String subject=s.length>4?s[4]:user;String state=memberships.get(subject);String json;if(path.contains("volunteer-membership")){boolean active="ACTIVE".equals(state);json=state==null?"{\"exists\":false,\"active\":false}":"{\"exists\":true,\"status\":\""+state+"\",\"active\":"+active+"}";}else json="{\"id\":\""+user+"\",\"systemRole\":\""+(ADMIN.equals(user)?"GOVERNANCE_ADMIN":"USER")+"\"}";byte[]b=json.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}}
}
