package org.animallink.incident;

import com.sun.net.httpserver.HttpExchange; import com.sun.net.httpserver.HttpServer;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.sql.Timestamp; import java.time.Instant; import java.util.*; import java.util.concurrent.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.*; import org.springframework.boot.test.context.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.*; import org.springframework.test.web.servlet.*; import org.testcontainers.containers.MySQLContainer; import org.testcontainers.junit.jupiter.*;
import static org.junit.jupiter.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers class CaseOwnerTransferIntegrationTest {
 static final String CAMPUS="51000000-0000-0000-0000-000000000001",A="51000000-0000-0000-0000-000000000011",B="51000000-0000-0000-0000-000000000012",C="51000000-0000-0000-0000-000000000013",ADMIN="51000000-0000-0000-0000-000000000015",REPORTER="51000000-0000-0000-0000-000000000014"; static final Stub STUB=new Stub();
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_owner_test").withUsername("test").withPassword("test");
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"a");r.add("animallink.minio.secret-key",()->"b");r.add("animallink.minio.bucket",()->"b");}
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
 @BeforeEach void clean(){STUB.members.clear();STUB.members.put(A,"ACTIVE");STUB.members.put(B,"ACTIVE");STUB.members.put(C,"ACTIVE");STUB.down=false;jdbc.update("DELETE FROM case_owner_audit_log");jdbc.update("DELETE FROM case_action_media");jdbc.update("DELETE FROM case_action");jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}
 @AfterAll static void stop(){STUB.stop();}
 @Test void activeTransferPreservesParticipantAndSwitchesOperationalPermissions() throws Exception {String id=seed("active","ACTIVE",A);participant(id,B);transfer(id,A,B).andExpect(status().isOk()).andExpect(jsonPath("$.ownerUserId").value(B));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM case_participant WHERE case_id=? AND user_id=?",String.class,id,B));mvc.perform(post("/api/v1/cases/{id}/result",id).header("X-User-Id",A).contentType("application/json").content("{\"outcome\":\"RESOLVED\",\"summary\":\"old\"}")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_RESULT_ACCESS_REQUIRED"));mvc.perform(post("/api/v1/cases/{id}/result",id).header("X-User-Id",B).contentType("application/json").content("{\"outcome\":\"RESOLVED\",\"summary\":\"new\"}")).andExpect(status().isOk());assertEquals(1,countAudit(id));}
 @Test void nonParticipantTargetCanTransferAndNewOwnerCanInvite() throws Exception {String id=seed("nonparticipant","ACTIVE",A);transfer(id,A,B).andExpect(status().isOk());mvc.perform(post("/api/v1/cases/{id}/participants/invitations",id).header("X-User-Id",B).contentType("application/json").content("{\"userId\":\""+C+"\"}")).andExpect(status().isOk());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM case_participant WHERE case_id=? AND user_id=?",Integer.class,id,C));}
 @Test void validationAndFailureContractsHaveNoMutation() throws Exception {String id=seed("errors","ACTIVE",A);transfer(id,C,B).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_OWNER_TRANSFER_OWNER_REQUIRED"));STUB.members.put(A,"PAUSED");transfer(id,A,B).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));STUB.members.put(A,"ACTIVE");STUB.members.put(B,"PAUSED");transfer(id,A,B).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("TARGET_ACTIVE_VOLUNTEER_REQUIRED"));STUB.members.put(B,"ACTIVE");transfer(id,A,A).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_OWNER_SAME_OWNER"));STUB.down=true;try{transfer(id,A,B).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));}finally{STUB.down=false;}assertEquals(A,owner(id));assertEquals(0,countAudit(id));}
 @Test void terminalCasesAreRejectedAndBusinessDataIsolated() throws Exception {for(String state:List.of("CLOSED","CLOSED_UNRESOLVED","CANCELLED")){String id=seed(state,state,A);transfer(id,A,B).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_OWNER_CHANGE_STATE_CONFLICT"));assertEquals(A,owner(id));}String id=seed("isolation","ACTIVE",A);jdbc.update("INSERT INTO case_action(id,case_id,actor_user_id,description,occurred_at,created_at) VALUES(?,?,?,?,?,?)","act",id,A,"a",Timestamp.from(Instant.now()),Timestamp.from(Instant.now()));transfer(id,A,B).andExpect(status().isOk());assertEquals("VERIFIED",jdbc.queryForObject("SELECT status FROM event WHERE id=?",String.class,"e-isolation"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM case_action WHERE case_id=?",Integer.class,id));assertNull(jdbc.queryForObject("SELECT result_code FROM animal_case WHERE id=?",String.class,id));}
 @Test void resolvedTransferPreservesResultAndNewOwnerCanClose() throws Exception {String id=seed("resolved","RESOLVED",A);Timestamp before=Timestamp.from(Instant.now());jdbc.update("UPDATE animal_case SET result_code='RESOLVED',result_summary='done',result_submitted_by_user_id=?,result_submitted_at=? WHERE id=?",A,before,id);transfer(id,A,B).andExpect(status().isOk());assertEquals("done",jdbc.queryForObject("SELECT result_summary FROM animal_case WHERE id=?",String.class,id));mvc.perform(post("/api/v1/cases/{id}/close",id).header("X-User-Id",A)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_CLOSE_OWNER_REQUIRED"));mvc.perform(post("/api/v1/cases/{id}/close",id).header("X-User-Id",B)).andExpect(status().isOk()).andExpect(jsonPath("$.caseStatus").value("CLOSED"));}
 @Test void governanceAdjustmentAndHistoryAuthorizationWork() throws Exception {String id=seed("admin","ACTIVE",A);STUB.members.put(A,"PAUSED");change(id,"/owner/adjustment",ADMIN,B).andExpect(status().isOk());Map<String,Object> row=jdbc.queryForList("SELECT * FROM case_owner_audit_log WHERE case_id=?",id).getFirst();assertEquals("GOVERNANCE_ADJUSTMENT",row.get("change_type"));assertEquals(ADMIN,row.get("changed_by_user_id"));change(id,"/owner/adjustment",C,B).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("GOVERNANCE_REQUIRED"));mvc.perform(get("/api/v1/cases/{id}/owner-history",id).header("X-User-Id",B)).andExpect(status().isOk()).andExpect(jsonPath("$[0].newOwnerUserId").value(B));participant(id,C);mvc.perform(get("/api/v1/cases/{id}/owner-history",id).header("X-User-Id",C)).andExpect(status().isOk());mvc.perform(get("/api/v1/cases/{id}/owner-history",id).header("X-User-Id",ADMIN)).andExpect(status().isOk());mvc.perform(get("/api/v1/cases/{id}/owner-history",id).header("X-User-Id",A)).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_OWNER_HISTORY_ACCESS_REQUIRED"));}
 @Test void consecutiveTransfersAppendOrderedAuditRows() throws Exception {String id=seed("chain","ACTIVE",A);transfer(id,A,B).andExpect(status().isOk());transfer(id,B,C).andExpect(status().isOk());List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM case_owner_audit_log WHERE case_id=? ORDER BY created_at,id",id);assertEquals(2,rows.size());assertEquals(A,rows.get(0).get("previous_owner_user_id"));assertEquals(B,rows.get(0).get("new_owner_user_id"));assertEquals(B,rows.get(1).get("previous_owner_user_id"));assertEquals(C,rows.get(1).get("new_owner_user_id"));}
 private ResultActions transfer(String id,String from,String to)throws Exception{return change(id,"/owner/transfer",from,to);} private ResultActions change(String id,String path,String from,String to)throws Exception{return mvc.perform(post("/api/v1/cases/{id}"+path,id).header("X-User-Id",from).contentType("application/json").content("{\"targetUserId\":\""+to+"\",\"reason\":\"handover\"}"));}
 private String seed(String x,String status,String owner){Timestamp n=Timestamp.from(Instant.now());String e="e-"+x,d="d-"+x,c="c-"+x;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,REPORTER,CAMPUS,"d",n,"p",n,n);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",e,d,REPORTER,CAMPUS,"e",n,n,"p","VERIFIED",n,n);jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",c,e,CAMPUS,owner,status,"CLAIMED",n,n,n);return c;}
 private void participant(String c,String u){Timestamp n=Timestamp.from(Instant.now());jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,"ACTIVE",A,n,n,n,n);} private String owner(String id){return jdbc.queryForObject("SELECT owner_user_id FROM animal_case WHERE id=?",String.class,id);} private int countAudit(String id){return jdbc.queryForObject("SELECT COUNT(*) FROM case_owner_audit_log WHERE case_id=?",Integer.class,id);}
 static class Stub {final HttpServer server;final Map<String,String> members=new ConcurrentHashMap<>();volatile boolean down;Stub(){try{server=HttpServer.create(new InetSocketAddress(0),0);server.createContext("/",this::handle);server.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+server.getAddress().getPort();}void stop(){server.stop(0);}void handle(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),h=e.getRequestHeaders().getFirst("X-User-Id");if(down&&p.contains("volunteer-membership")){e.sendResponseHeaders(503,-1);e.close();return;}String[] parts=p.split("/");String u=parts.length>4?parts[4]:h;String json=p.contains("volunteer-membership")?("ACTIVE".equals(members.get(u))?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"exists\":true,\"active\":false,\"status\":\"PAUSED\"}"):"{\"id\":\""+h+"\",\"systemRole\":\""+(ADMIN.equals(h)?"GOVERNANCE_ADMIN":"USER")+"\"}";byte[] b=json.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}}
}
