package org.animallink.incident;

import com.sun.net.httpserver.HttpExchange;import com.sun.net.httpserver.HttpServer;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.sql.Timestamp;import java.time.Instant;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.*;import org.springframework.boot.test.context.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.*;import org.testcontainers.containers.MySQLContainer;import org.testcontainers.junit.jupiter.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers class CaseResultConcurrencyIntegrationTest {
 static final String CAMPUS="40000000-0000-0000-0000-000000000001",OWNER="40000000-0000-0000-0000-000000000011",TARGET="40000000-0000-0000-0000-000000000012",REPORTER="40000000-0000-0000-0000-000000000014";static final Stub STUB=new Stub();
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_result_concurrency_test").withUsername("test").withPassword("test");
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"a");r.add("animallink.minio.secret-key",()->"b");r.add("animallink.minio.bucket",()->"b");}
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @BeforeEach void clean(){jdbc.update("DELETE FROM case_action_media");jdbc.update("DELETE FROM case_action");jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}
 @AfterAll static void stop(){STUB.stop();}
 @Test void terminalResultsHaveExactlyOneWinnerAcrossFiveRounds() throws Exception {ExecutorService pool=Executors.newFixedThreadPool(2);try{for(int round=0;round<5;round++){String c=seed("r"+round);CountDownLatch ready=new CountDownLatch(2),go=new CountDownLatch(1);Future<Result> owner=pool.submit(()->call(c,OWNER,"RESOLVED",ready,go));Future<Result> target=pool.submit(()->call(c,TARGET,"CANCELLED",ready,go));assertTrue(ready.await(10,TimeUnit.SECONDS));go.countDown();List<Result> results=List.of(owner.get(20,TimeUnit.SECONDS),target.get(20,TimeUnit.SECONDS));assertEquals(1,results.stream().filter(x->x.status==200).count());assertEquals(1,results.stream().filter(x->x.status==409).count());assertTrue(results.stream().filter(x->x.status==409).allMatch(x->x.body.contains("CASE_RESULT_STATE_CONFLICT")));assertTrue(results.stream().noneMatch(x->x.status>=500));Map<String,Object> row=jdbc.queryForList("SELECT status,result_code,result_submitted_by_user_id FROM animal_case WHERE id=?",c).getFirst();String status=row.get("status").toString(),code=row.get("result_code").toString(),winner=results.stream().filter(x->x.status==200).findFirst().orElseThrow().user;assertEquals("RESOLVED".equals(status)?"RESOLVED":"CANCELLED",code);assertEquals(winner,row.get("result_submitted_by_user_id"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM case_action WHERE case_id=? AND result_code IN ('RESOLVED','CANCELLED')",Integer.class,c));}}finally{pool.shutdownNow();}}
 private Result call(String c,String user,String outcome,CountDownLatch ready,CountDownLatch go)throws Exception{ready.countDown();go.await(10,TimeUnit.SECONDS);MvcResult r=mvc.perform(post("/api/v1/cases/{id}/result",c).header("X-User-Id",user).contentType("application/json").content("{\"outcome\":\""+outcome+"\",\"summary\":\""+outcome+"\"}")).andReturn();return new Result(user,r.getResponse().getStatus(),r.getResponse().getContentAsString());}
 private String seed(String x){Timestamp n=Timestamp.from(Instant.now());String e="e-"+x,d="d-"+x,c="c-"+x;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,REPORTER,CAMPUS,"d",n,"p",n,n);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",e,d,REPORTER,CAMPUS,"e",n,n,"p","VERIFIED",n,n);jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",c,e,CAMPUS,OWNER,"ACTIVE","CLAIMED",n,n,n);jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,TARGET,"ACTIVE",OWNER,n,n,n,n);return c;}
 record Result(String user,int status,String body){}
 static class Stub{final HttpServer h;Stub(){try{h=HttpServer.create(new InetSocketAddress(0),0);h.createContext("/",this::x);h.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+h.getAddress().getPort();}void stop(){h.stop(0);}void x(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),u=e.getRequestHeaders().getFirst("X-User-Id");String[]a=p.split("/");String q=a.length>4?a[4]:u;String z=p.contains("volunteer-membership")?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"id\":\""+u+"\",\"systemRole\":\"USER\"}";byte[]b=z.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}}
}
