package org.animallink.incident;

import com.sun.net.httpserver.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.sql.Timestamp; import java.time.Instant; import java.util.*; import java.util.concurrent.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.*; import org.springframework.boot.test.context.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.*; import org.springframework.test.web.servlet.*; import org.testcontainers.containers.MySQLContainer; import org.testcontainers.junit.jupiter.*; import static org.junit.jupiter.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers class CaseOwnerTransferConcurrencyIntegrationTest {
 static final String CAMPUS="52000000-0000-0000-0000-000000000001",A="52000000-0000-0000-0000-000000000011",B="52000000-0000-0000-0000-000000000012",C="52000000-0000-0000-0000-000000000013",REPORTER="52000000-0000-0000-0000-000000000014";static final Stub STUB=new Stub();@Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_owner_concurrency_test").withUsername("test").withPassword("test");
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"a");r.add("animallink.minio.secret-key",()->"b");r.add("animallink.minio.bucket",()->"b");}
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@BeforeEach void clean(){jdbc.update("DELETE FROM case_owner_audit_log");jdbc.update("DELETE FROM case_action_media");jdbc.update("DELETE FROM case_action");jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}@AfterAll static void stop(){STUB.stop();}
 @Test void exactlyOneTransferAndAuditWinAcrossFiveRounds() throws Exception {ExecutorService pool=Executors.newFixedThreadPool(2);try{for(int round=0;round<5;round++){String id=seed("r"+round);CountDownLatch ready=new CountDownLatch(2),go=new CountDownLatch(1);Future<Result> b=pool.submit(()->call(id,B,ready,go));Future<Result> c=pool.submit(()->call(id,C,ready,go));assertTrue(ready.await(10,TimeUnit.SECONDS));go.countDown();List<Result> rs=List.of(b.get(20,TimeUnit.SECONDS),c.get(20,TimeUnit.SECONDS));assertEquals(1,rs.stream().filter(x->x.status==200).count());assertEquals(1,rs.stream().filter(x->x.status==409).count());assertTrue(rs.stream().filter(x->x.status==409).allMatch(x->x.body.contains("CASE_OWNER_CHANGE_CONFLICT")));assertTrue(rs.stream().noneMatch(x->x.status>=500));String winner=rs.stream().filter(x->x.status==200).findFirst().orElseThrow().target;assertEquals(winner,jdbc.queryForObject("SELECT owner_user_id FROM animal_case WHERE id=?",String.class,id));Map<String,Object> audit=jdbc.queryForList("SELECT * FROM case_owner_audit_log WHERE case_id=?",id).getFirst();assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM case_owner_audit_log WHERE case_id=?",Integer.class,id));assertEquals(A,audit.get("previous_owner_user_id"));assertEquals(winner,audit.get("new_owner_user_id"));}}finally{pool.shutdownNow();}}
 private Result call(String id,String target,CountDownLatch ready,CountDownLatch go)throws Exception{ready.countDown();go.await(10,TimeUnit.SECONDS);MvcResult r=mvc.perform(post("/api/v1/cases/{id}/owner/transfer",id).header("X-User-Id",A).contentType("application/json").content("{\"targetUserId\":\""+target+"\",\"reason\":\"race\"}")).andReturn();return new Result(target,r.getResponse().getStatus(),r.getResponse().getContentAsString());}
 private String seed(String x){Timestamp n=Timestamp.from(Instant.now());String d="d-"+x,e="e-"+x,c="c-"+x;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,REPORTER,CAMPUS,"d",n,"p",n,n);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",e,d,REPORTER,CAMPUS,"e",n,n,"p","VERIFIED",n,n);jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",c,e,CAMPUS,A,"ACTIVE","CLAIMED",n,n,n);return c;}record Result(String target,int status,String body){}
 static class Stub{final HttpServer s;Stub(){try{s=HttpServer.create(new InetSocketAddress(0),0);s.createContext("/",this::x);s.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+s.getAddress().getPort();}void stop(){s.stop(0);}void x(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),h=e.getRequestHeaders().getFirst("X-User-Id");String z=p.contains("volunteer-membership")?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"id\":\""+h+"\",\"systemRole\":\"USER\"}";byte[]b=z.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}}
}
