package org.animallink.incident;

import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.sql.Timestamp;import java.time.Instant;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.*;import org.springframework.boot.test.context.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.containers.MySQLContainer;import org.testcontainers.junit.jupiter.*;import static org.hamcrest.Matchers.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers class CaseActionIntegrationTest {static final String C="10000000-0000-0000-0000-000000000101",O="00000000-0000-0000-0000-000000000201",T="00000000-0000-0000-0000-000000000202",X="00000000-0000-0000-0000-000000000203",R="00000000-0000-0000-0000-000000000204";static final Stub S=new Stub();@Container static final MySQLContainer<?> M=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("case_action_test").withUsername("test").withPassword("test");@DynamicPropertySource static void p(DynamicPropertyRegistry r){r.add("spring.datasource.url",M::getJdbcUrl);r.add("spring.datasource.username",M::getUsername);r.add("spring.datasource.password",M::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",S::url);r.add("animallink.animal.base-url",S::url);r.add("animallink.intelligence.base-url",S::url);r.add("animallink.minio.endpoint",()->"http://localhost:9000");r.add("animallink.minio.access-key",()->"a");r.add("animallink.minio.secret-key",()->"b");r.add("animallink.minio.bucket",()->"b");}@Autowired MockMvc mvc;@Autowired JdbcTemplate j;@BeforeEach void clean(){S.m.clear();S.m.put(O,"ACTIVE");S.m.put(T,"ACTIVE");S.m.put(X,"ACTIVE");j.update("DELETE FROM case_action");j.update("DELETE FROM case_participant");j.update("DELETE FROM animal_case");j.update("DELETE FROM evidence");j.update("DELETE FROM event");j.update("DELETE FROM event_draft");}@AfterAll static void stop(){S.stop();}
 static final String A="00000000-0000-0000-0000-000000000999";
 @Test void ownerCanCreateCaseAction()throws Exception{String c=seed("owner");int e=count("evidence");mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",O).contentType("application/json").content("{\"description\":\"x\",\"occurredAt\":\"2026-10-03T10:00:00Z\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.actorUserId").value(O));assertEquals(1,count("case_action"));assertEquals(e,count("evidence"));assertEquals("ACTIVE",j.queryForObject("SELECT status FROM animal_case WHERE id=?",String.class,c));}
 @Test void activeCollaboratorCanCreateCaseAction()throws Exception{String c=seed("active");participant(c,T,"ACTIVE");create(c,T).andExpect(status().isOk()).andExpect(jsonPath("$.actorUserId").value(T));}
 @Test void unrelatedActiveVolunteerCannotCreateCaseAction()throws Exception{String c=seed("other");create(c,X).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));assertEquals(0,count("case_action"));}
 @Test void inactiveOwnerCannotCreateCaseAction()throws Exception{String c=seed("paused");S.m.put(O,"PAUSED");create(c,O).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));assertEquals(0,count("case_action"));}
 @Test void nonActiveCaseCannotCreateCaseAction()throws Exception{String c=seed("resolved");j.update("UPDATE animal_case SET status='RESOLVED' WHERE id=?",c);create(c,O).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CASE_NOT_ACTIVE"));assertEquals(0,count("case_action"));}
 @Test void ownerCanListActions()throws Exception{String c=seed("list-owner");action(c,"owner-action","2026-10-03T10:00:00Z","2026-10-03T10:01:00Z");list(c,O).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].actorUserId").value(O)).andExpect(jsonPath("$.total").value(1));}
 @Test void actionListExposesNullableAndAllResultCodes()throws Exception{String c=seed("result-code");String[] codes={"CONTINUE_OBSERVATION","RESOLVED","UNRESOLVED","CANCELLED"};for(int i=0;i<codes.length;i++){String id="result-"+i;action(c,id,"2026-10-03T10:0"+i+":00Z","2026-10-03T10:1"+i+":00Z");j.update("UPDATE case_action SET result_code=? WHERE id=?",codes[i],id);}list(c,O).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].resultCode").value("CONTINUE_OBSERVATION")).andExpect(jsonPath("$.items[1].resultCode").value("RESOLVED")).andExpect(jsonPath("$.items[2].resultCode").value("UNRESOLVED")).andExpect(jsonPath("$.items[3].resultCode").value("CANCELLED"));String plain=seed("plain-code");action(plain,"plain","2026-10-03T10:00:00Z","2026-10-03T10:01:00Z");list(plain,O).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].resultCode").doesNotExist());}
 @Test void activeParticipantCanListActions()throws Exception{String c=seed("list-active");participant(c,T,"ACTIVE");action(c,"active-action","2026-10-03T10:00:00Z","2026-10-03T10:01:00Z");list(c,T).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].id").value("active-action"));}
 @Test void governanceAdminCanListActions()throws Exception{String c=seed("list-admin");action(c,"admin-action","2026-10-03T10:00:00Z","2026-10-03T10:01:00Z");list(c,A).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].id").value("admin-action"));}
 @Test void unrelatedActiveVolunteerCannotListActions()throws Exception{String c=seed("list-other");list(c,X).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 @Test void leftParticipantCannotListActions()throws Exception{String c=seed("list-left");leftParticipant(c,T);list(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 @Test void multipleActionsAreReturnedInChronologicalOrder()throws Exception{String c=seed("list-order");action(c,"z","2026-10-03T10:00:00Z","2026-10-03T10:01:00Z");action(c,"b","2026-10-03T09:00:00Z","2026-10-03T12:00:00Z");action(c,"c","2026-10-03T10:00:00Z","2026-10-03T10:00:00Z");action(c,"a","2026-10-03T10:00:00Z","2026-10-03T10:00:00Z");list(c,O,0,2).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(4)).andExpect(jsonPath("$.page").value(0)).andExpect(jsonPath("$.size").value(2)).andExpect(jsonPath("$.items[0].id").value("b")).andExpect(jsonPath("$.items[1].id").value("a"));}
 @Test void identityUnavailableDoesNotCreateAction()throws Exception{String c=seed("identity-down");S.unavailable=true;try{create(c,O).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("IDENTITY_SERVICE_UNAVAILABLE"));}finally{S.unavailable=false;}assertEquals(0,count("case_action"));}
 @Test void revokedActiveParticipantCannotCreateAction()throws Exception{String c=seed("revoked");participant(c,T,"ACTIVE");S.m.put(T,"REVOKED");create(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));assertEquals(0,count("case_action"));}
 @Test void invitedParticipantCannotCreateAction()throws Exception{String c=seed("invited-post");participantState(c,T,"INVITED");create(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 @Test void declinedParticipantCannotCreateAction()throws Exception{String c=seed("declined-post");participantState(c,T,"DECLINED");create(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 @Test void removedParticipantCannotCreateAction()throws Exception{String c=seed("removed-post");participantState(c,T,"REMOVED");create(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 @Test void missingCasePostAndGetReturnCaseNotFound()throws Exception{create("missing",O).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("CASE_NOT_FOUND"));list("missing",O).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("CASE_NOT_FOUND"));}
 @Test void invalidActionRequestsReturnValidationError()throws Exception{String c=seed("validation");mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",O).contentType("application/json").content("{\"description\":\" \",\"occurredAt\":\"2026-10-03T10:00:00Z\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",O).contentType("application/json").content("{\"description\":\"x\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));}
 @Test void invalidPaginationReturnsValidationError()throws Exception{String c=seed("pagination-validation");for(String[] value:List.of(new String[]{"page","-1"},new String[]{"size","0"},new String[]{"size","101"}))mvc.perform(get("/api/v1/cases/{id}/actions",c).header("X-User-Id",O).param(value[0],value[1])).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));}
 @Test void terminalParticipantsCannotListActions()throws Exception{for(String state:List.of("INVITED","DECLINED","REMOVED")){String c=seed("list-"+state);participantState(c,T,state);list(c,T).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}}
 @Test void governanceAdminCannotCreateAction()throws Exception{String c=seed("admin-post");create(c,A).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("CASE_ACTION_ACCESS_REQUIRED"));}
 private org.springframework.test.web.servlet.ResultActions list(String c,String u)throws Exception{return list(c,u,0,20);}private org.springframework.test.web.servlet.ResultActions list(String c,String u,int page,int size)throws Exception{return mvc.perform(get("/api/v1/cases/{id}/actions",c).header("X-User-Id",u).param("page",String.valueOf(page)).param("size",String.valueOf(size)));}private void action(String c,String id,String occurred,String created){j.update("INSERT INTO case_action(id,case_id,actor_user_id,description,occurred_at,created_at) VALUES(?,?,?,?,?,?)",id,c,O,"action-"+id,Timestamp.from(Instant.parse(occurred)),Timestamp.from(Instant.parse(created)));}private void leftParticipant(String c,String u){Timestamp n=Timestamp.from(Instant.now());j.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,ended_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,"LEFT",O,n,n,n,n,n);}private void participantState(String c,String u,String state){Timestamp n=Timestamp.from(Instant.now());if("INVITED".equals(state))j.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,state,O,n,n,n);else if("DECLINED".equals(state))j.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,ended_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,state,O,n,n,n,n);else j.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,ended_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,state,O,n,n,n,n,n);}
 private org.springframework.test.web.servlet.ResultActions create(String c,String u)throws Exception{return mvc.perform(post("/api/v1/cases/{id}/actions",c).header("X-User-Id",u).contentType("application/json").content("{\"description\":\"x\",\"occurredAt\":\"2026-10-03T10:00:00Z\"}"));}private int count(String t){return j.queryForObject("SELECT COUNT(*) FROM "+t,Integer.class);}private String seed(String x){Timestamp n=Timestamp.from(Instant.now());String e="e-"+x,d="d-"+x,c="c-"+x;j.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,R,C,"d",n,"p",n,n);j.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,description,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",e,d,R,C,"e",n,n,"p","VERIFIED",n,n);j.update("INSERT INTO animal_case(id,event_id,campus_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",c,e,C,O,"ACTIVE","CLAIMED",n,n,n);return c;}private void participant(String c,String u,String s){Timestamp n=Timestamp.from(Instant.now());j.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,u,s,O,n,n,n,n);}static class Stub{final HttpServer h;final Map<String,String>m=new ConcurrentHashMap<>();volatile boolean unavailable;Stub(){try{h=HttpServer.create(new InetSocketAddress(0),0);h.createContext("/",this::x);h.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+h.getAddress().getPort();}void stop(){h.stop(0);}void x(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),u=e.getRequestHeaders().getFirst("X-User-Id");if(unavailable&&p.contains("volunteer-membership")){e.sendResponseHeaders(503,-1);e.close();return;}String[]a=p.split("/");String q=a.length>4?a[4]:u;String z=p.contains("volunteer-membership")?("ACTIVE".equals(m.get(q))?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"exists\":true,\"active\":false,\"status\":\"PAUSED\"}"):"{\"id\":\""+u+"\",\"systemRole\":\""+(A.equals(u)?"GOVERNANCE_ADMIN":"USER")+"\"}";byte[]b=z.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}}}
