package org.animallink.incident;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import java.io.IOException;import java.net.InetSocketAddress;import java.nio.charset.StandardCharsets;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@Testcontainers
class EventDraftIntegrationTest {
 @DynamicPropertySource static void minioBucket(DynamicPropertyRegistry r){r.add("animallink.minio.bucket",()->"animallink-incident");}
 static final String CAMPUS="10000000-0000-0000-0000-000000000101", OWNER="00000000-0000-0000-0000-000000000101", OTHER="00000000-0000-0000-0000-000000000102";
 @DynamicPropertySource static void minioContainer(DynamicPropertyRegistry r){r.add("animallink.minio.endpoint",()->"http://"+MINIO.getHost()+":"+MINIO.getMappedPort(9000));r.add("animallink.minio.access-key",()->"minioadmin");r.add("animallink.minio.secret-key",()->"minioadmin");}
 static final Stub IDENTITY=new Stub();
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("incident_test").withUsername("test").withPassword("test");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",IDENTITY::url);r.add("animallink.animal.base-url",IDENTITY::url);r.add("animallink.intelligence.base-url",IDENTITY::url);}
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@Autowired ObjectMapper objectMapper;@Autowired io.minio.MinioClient minio;
 @BeforeEach void clean() throws Exception {IDENTITY.reset();if(!minio.bucketExists(io.minio.BucketExistsArgs.builder().bucket("animallink-incident").build()))minio.makeBucket(io.minio.MakeBucketArgs.builder().bucket("animallink-incident").build());jdbc.update("DELETE FROM event_draft_media");jdbc.update("DELETE FROM event_draft");}
 @Container static final org.testcontainers.containers.GenericContainer<?> MINIO=new org.testcontainers.containers.GenericContainer<>("animallink-minio:RELEASE.2025-10-15T17-29-55Z").withExposedPorts(9000).withEnv("MINIO_ROOT_USER","minioadmin").withEnv("MINIO_ROOT_PASSWORD","minioadmin").withCommand("server /data");
 @AfterAll static void stop(){IDENTITY.stop();}
 @Test void createGetAndPatchManualDraft() throws Exception {String body="{\"campusId\":\""+CAMPUS+"\",\"description\":\"initial\",\"occurredAt\":\"2026-10-01T00:00:00Z\",\"publicLocationDescription\":\"public\",\"exactLocationDescription\":\"exact\"}";String response=mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.description").value("initial")).andReturn().getResponse().getContentAsString();String id=objectMapper.readTree(response).required("id").asText();org.junit.jupiter.api.Assertions.assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM event_draft WHERE id=? AND animal_id IS NULL",Integer.class,id));mvc.perform(get("/api/v1/event-drafts/{id}",id).header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.exactLocationDescription").value("exact"));String patched=body.replace("initial","patched");mvc.perform(patch("/api/v1/event-drafts/{id}",id).header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(patched)).andExpect(status().isOk()).andExpect(jsonPath("$.description").value("patched"));}
 @Test void nonOwnerCannotReadOrPatchDraft() throws Exception {String id=seed();String body=draftBody("");mvc.perform(get("/api/v1/event-drafts/{id}",id).header("X-User-Id",OTHER)).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("EVENT_DRAFT_NOT_FOUND"));mvc.perform(patch("/api/v1/event-drafts/{id}",id).header("X-User-Id",OTHER).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("EVENT_DRAFT_NOT_FOUND"));}
 @Test void finalizedDraftRejectsPatchAndReplacesDraftMedia() throws Exception {String id=create(draftBody(",\"media\":[{\"temporaryObjectKey\":\"incident-input/owner/first.jpg\",\"contentType\":\"image/jpeg\",\"sizeBytes\":12,\"sortOrder\":0}]"));mvc.perform(get("/api/v1/event-drafts/{id}",id).header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.media[0].contentType").value("image/jpeg"));org.junit.jupiter.api.Assertions.assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM event_draft_media WHERE event_draft_id=?",Integer.class,id));String replacement=draftBody(",\"media\":[{\"temporaryObjectKey\":\"incident-input/owner/replacement.mp4\",\"contentType\":\"video/mp4\",\"sizeBytes\":24,\"sortOrder\":1}]");mvc.perform(patch("/api/v1/event-drafts/{id}",id).header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(replacement)).andExpect(status().isOk()).andExpect(jsonPath("$.media[0].contentType").value("video/mp4"));org.junit.jupiter.api.Assertions.assertEquals("incident-input/owner/replacement.mp4",jdbc.queryForObject("SELECT temporary_object_key FROM event_draft_media WHERE event_draft_id=?",String.class,id));jdbc.update("UPDATE event_draft SET final_event_id=? WHERE id=?","10000000-0000-0000-0000-000000000999",id);mvc.perform(patch("/api/v1/event-drafts/{id}",id).header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(replacement)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("EVENT_DRAFT_FINALIZED"));}
 @Test void acceptsAndRejectsAiAndMatchingProvenance() throws Exception {String ai=create(draftBody(",\"sourceAiTaskId\":\"ai-valid\""));org.junit.jupiter.api.Assertions.assertEquals("ai-valid",jdbc.queryForObject("SELECT source_ai_task_id FROM event_draft WHERE id=?",String.class,ai));mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"sourceAiTaskId\":\"invalid-ai\""))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("INVALID_PROVENANCE"));String match=create(draftBody(",\"sourceAiTaskId\":\"ai-valid\",\"sourceMatchingRecordId\":\"match-valid\""));org.junit.jupiter.api.Assertions.assertEquals("match-valid",jdbc.queryForObject("SELECT source_matching_record_id FROM event_draft WHERE id=?",String.class,match));mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"sourceAiTaskId\":\"ai-valid\",\"sourceMatchingRecordId\":\"match-mismatch\""))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("INVALID_PROVENANCE"));}
 @Test void acceptsAndRejectsPostProvenanceAndUnavailableIntelligence() throws Exception {String post=create(draftBody(",\"sourcePostId\":\"post-valid\""));org.junit.jupiter.api.Assertions.assertEquals("post-valid",jdbc.queryForObject("SELECT source_post_id FROM event_draft WHERE id=?",String.class,post));mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"sourcePostId\":\"invalid-post\""))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("INVALID_PROVENANCE"));IDENTITY.intelligenceUnavailable=true;mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"sourceAiTaskId\":\"ai-valid\""))).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("INTELLIGENCE_SERVICE_UNAVAILABLE"));}
 @Test void validatesAnimalFactsAndUnavailableAnimalService() throws Exception {String same=create(draftBody(",\"animalId\":\"same-animal\""));org.junit.jupiter.api.Assertions.assertEquals("same-animal",jdbc.queryForObject("SELECT animal_id FROM event_draft WHERE id=?",String.class,same));mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"animalId\":\"cross-animal\""))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CROSS_CAMPUS_ANIMAL"));mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"animalId\":\"archived-animal\""))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ANIMAL_NOT_ACTIVE"));IDENTITY.animalUnavailable=true;mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(draftBody(",\"animalId\":\"same-animal\""))).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.code").value("ANIMAL_SERVICE_UNAVAILABLE"));}
 private String seed() throws Exception {return create(draftBody(""));}
 private String create(String body) throws Exception {String response=mvc.perform(post("/api/v1/event-drafts").header("X-User-Id",OWNER).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return objectMapper.readTree(response).required("id").asText();}
 private String draftBody(String suffix){return "{\"campusId\":\""+CAMPUS+"\",\"description\":\"d\",\"occurredAt\":\"2026-10-01T00:00:00Z\",\"publicLocationDescription\":\"p\""+suffix+"}";}
 static class Stub {final HttpServer server;volatile boolean intelligenceUnavailable,animalUnavailable;Stub(){try{server=HttpServer.create(new InetSocketAddress(0),0);server.createContext("/",this::handle);server.start();}catch(IOException e){throw new RuntimeException(e);}}void reset(){intelligenceUnavailable=false;animalUnavailable=false;}String url(){return "http://localhost:"+server.getAddress().getPort();}void stop(){server.stop(0);}void handle(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),u=e.getRequestHeaders().getFirst("X-User-Id");int status=200;String json;if(p.endsWith("/me"))json="{\"id\":\""+(u==null?OWNER:u)+"\",\"systemRole\":\"USER\"}";else if(p.contains("campus-memberships"))json="{\"exists\":true,\"status\":\"ACTIVE\"}";else if(p.contains("/animals/")){if(animalUnavailable){status=503;json="{}";}else if(p.endsWith("cross-animal"))json="{\"campusId\":\"other-campus\",\"identityStatus\":\"ACTIVE\"}";else if(p.endsWith("archived-animal"))json="{\"campusId\":\""+CAMPUS+"\",\"identityStatus\":\"ARCHIVED\"}";else json="{\"campusId\":\""+CAMPUS+"\",\"identityStatus\":\"ACTIVE\"}";}else if(p.contains("/ai-tasks/")){if(intelligenceUnavailable){status=503;json="{}";}else if(p.endsWith("invalid-ai"))json="{\"ownerUserId\":\""+OTHER+"\",\"campusId\":\""+CAMPUS+"\",\"status\":\"SUCCEEDED\",\"confirmed\":true}";else json="{\"ownerUserId\":\""+OWNER+"\",\"campusId\":\""+CAMPUS+"\",\"status\":\"SUCCEEDED\",\"confirmed\":true}";}else if(p.contains("/matches/")){if(intelligenceUnavailable){status=503;json="{}";}else json="{\"ownerUserId\":\""+OWNER+"\",\"campusId\":\""+CAMPUS+"\",\"aiTaskId\":\""+(p.endsWith("match-mismatch")?"other-ai":"ai-valid")+"\"}";}else if(p.contains("/posts/"))json=p.endsWith("invalid-post")?"{\"authorUserId\":\""+OTHER+"\",\"campusId\":\""+CAMPUS+"\",\"status\":\"ACTIVE\"}":"{\"authorUserId\":\""+OWNER+"\",\"campusId\":\""+CAMPUS+"\",\"status\":\"ACTIVE\"}";else json="{}";byte[] bytes=json.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(status,bytes.length);e.getResponseBody().write(bytes);e.close();}}
}