package org.animallink.incident;

import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.util.UUID;import java.util.concurrent.*;
import org.animallink.incident.infrastructure.CaseResultOutboxPublisher;import org.junit.jupiter.api.*;import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.connection.CachingConnectionFactory;import org.springframework.amqp.rabbit.connection.CorrelationData;import org.springframework.amqp.rabbit.core.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import org.testcontainers.containers.MySQLContainer;import org.testcontainers.containers.RabbitMQContainer;import org.testcontainers.junit.jupiter.*;import org.testcontainers.utility.DockerImageName;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

@SpringBootTest @Testcontainers class OutboxPublisherIntegrationTest {
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("outbox_publisher_test").withUsername("test").withPassword("test");
 @Container static final RabbitMQContainer RABBIT=new RabbitMQContainer(DockerImageName.parse("rabbitmq:3.13-management"));
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);}
 @Autowired JdbcTemplate jdbc;@Autowired PlatformTransactionManager tx;@Autowired ObjectMapper json;CachingConnectionFactory connection;RabbitTemplate rabbit;CaseResultOutboxPublisher publisher;
 @BeforeEach void setup(){jdbc.update("DELETE FROM outbox_event");connection=new CachingConnectionFactory(RABBIT.getHost(),RABBIT.getAmqpPort());connection.setUsername(RABBIT.getAdminUsername());connection.setPassword(RABBIT.getAdminPassword());connection.setPublisherConfirmType(CachingConnectionFactory.ConfirmType.CORRELATED);rabbit=new RabbitTemplate(connection);RabbitAdmin admin=new RabbitAdmin(connection);TopicExchange exchange=new TopicExchange("animallink.domain",true,false);Queue queue=new Queue("animal.timeline.case-result",true,false,false);admin.declareExchange(exchange);admin.declareQueue(queue);admin.declareBinding(BindingBuilder.bind(queue).to(exchange).with("incident.case.result-finalized"));admin.purgeQueue(queue.getName(),true);publisher=new CaseResultOutboxPublisher(jdbc,rabbit,new TransactionTemplate(tx));}
 @AfterEach void close(){connection.destroy();}
 @Test void pendingPublishesWithConfirmAndPublishedRowsAreNotResent()throws Exception{String id=pending();assertEquals(1,publisher.publishBatch());Object received=rabbit.receiveAndConvert("animal.timeline.case-result",3000);assertNotNull(received);String payload=received instanceof byte[] bytes?new String(bytes,StandardCharsets.UTF_8):received.toString();assertEquals(id,json.readTree(payload).get("eventId").asText());var row=jdbc.queryForMap("SELECT * FROM outbox_event WHERE id=?",id);assertEquals("PUBLISHED",row.get("status"));assertNotNull(row.get("published_at"));assertEquals(0,publisher.publishBatch());assertNull(rabbit.receiveAndConvert("animal.timeline.case-result",300));}
 @Test void unavailableBrokerKeepsPendingAndAdvancesRetry(){String id=pending();CachingConnectionFactory down=new CachingConnectionFactory("127.0.0.1",1);down.setPublisherConfirmType(CachingConnectionFactory.ConfirmType.CORRELATED);try{CaseResultOutboxPublisher failing=new CaseResultOutboxPublisher(jdbc,new RabbitTemplate(down),new TransactionTemplate(tx));assertEquals(0,failing.publishBatch());var row=jdbc.queryForMap("SELECT * FROM outbox_event WHERE id=?",id);assertEquals("PENDING",row.get("status"));assertEquals(1,((Number)row.get("attempt_count")).intValue());assertNotNull(row.get("last_error"));assertEquals(1,jdbc.queryForObject("SELECT available_at>CURRENT_TIMESTAMP(6) FROM outbox_event WHERE id=?",Integer.class,id));}finally{down.destroy();}}
 @Test void brokerNackKeepsPendingAndAdvancesRetry(){String id=pending();RabbitTemplate nack=mock(RabbitTemplate.class);doAnswer(call->{CorrelationData correlation=call.getArgument(4);correlation.getFuture().complete(new CorrelationData.Confirm(false,"test nack"));return null;}).when(nack).convertAndSend(anyString(),anyString(),any(),any(MessagePostProcessor.class),any(CorrelationData.class));CaseResultOutboxPublisher failing=new CaseResultOutboxPublisher(jdbc,nack,new TransactionTemplate(tx));assertEquals(0,failing.publishBatch());var row=jdbc.queryForMap("SELECT * FROM outbox_event WHERE id=?",id);assertEquals("PENDING",row.get("status"));assertEquals(1,((Number)row.get("attempt_count")).intValue());assertEquals("test nack",row.get("last_error"));assertEquals(1,jdbc.queryForObject("SELECT available_at>CURRENT_TIMESTAMP(6) FROM outbox_event WHERE id=?",Integer.class,id));}
 @Test void confirmTimeoutKeepsPendingAndAdvancesRetry(){String id=pending();RabbitTemplate timeout=mock(RabbitTemplate.class);CaseResultOutboxPublisher failing=new CaseResultOutboxPublisher(jdbc,timeout,new TransactionTemplate(tx));assertEquals(0,failing.publishBatch());var row=jdbc.queryForMap("SELECT * FROM outbox_event WHERE id=?",id);assertEquals("PENDING",row.get("status"));assertEquals(1,((Number)row.get("attempt_count")).intValue());assertNotNull(row.get("last_error"));assertEquals(1,jdbc.queryForObject("SELECT available_at>CURRENT_TIMESTAMP(6) FROM outbox_event WHERE id=?",Integer.class,id));}
 @Test void concurrentWorkersPublishLockedRowOnce()throws Exception{pending();ExecutorService pool=Executors.newFixedThreadPool(2);try{Future<Integer>a=pool.submit(publisher::publishBatch),b=pool.submit(publisher::publishBatch);assertEquals(1,a.get(10,TimeUnit.SECONDS)+b.get(10,TimeUnit.SECONDS));assertNotNull(rabbit.receiveAndConvert("animal.timeline.case-result",3000));assertNull(rabbit.receiveAndConvert("animal.timeline.case-result",300));}finally{pool.shutdownNow();}}
 private String pending(){String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO outbox_event(id,aggregate_type,aggregate_id,event_type,payload_json,status,available_at,created_at,updated_at) VALUES(?,'CASE',?,'CASE_RESULT_FINALIZED',CAST(? AS JSON),'PENDING',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6))",id,UUID.randomUUID().toString(),"{\"eventId\":\""+id+"\"}");return id;}
}
