package org.animallink.incident;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import io.minio.BucketExistsArgs;
import io.minio.MakeBucketArgs;
import io.minio.MinioClient;
import io.minio.PutObjectArgs;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest @AutoConfigureMockMvc @Testcontainers
class RescueQueryIntegrationTest {
  static final String CAMPUS="61000000-0000-0000-0000-000000000001", OWNER="61000000-0000-0000-0000-000000000011", TARGET="61000000-0000-0000-0000-000000000012", OTHER="61000000-0000-0000-0000-000000000013", REPORTER="61000000-0000-0000-0000-000000000014", ADMIN="61000000-0000-0000-0000-000000000015";
  static final Stub STUB=new Stub();
  static final String BUCKET="rescue-query-media";
  @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>("mysql:8.0.41").withDatabaseName("rescue_query_test").withUsername("test").withPassword("test");
  @Container static final GenericContainer<?> MINIO=new GenericContainer<>("animallink-minio:RELEASE.2025-10-15T17-29-55Z").withExposedPorts(9000).withEnv("MINIO_ROOT_USER","minioadmin").withEnv("MINIO_ROOT_PASSWORD","minioadmin").withCommand("server /data");
  @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);r.add("spring.cloud.nacos.discovery.enabled",()->false);r.add("spring.cloud.nacos.config.enabled",()->false);r.add("animallink.identity.base-url",STUB::url);r.add("animallink.animal.base-url",STUB::url);r.add("animallink.intelligence.base-url",STUB::url);r.add("animallink.minio.endpoint",()->"http://"+MINIO.getHost()+":"+MINIO.getMappedPort(9000));r.add("animallink.minio.access-key",()->"minioadmin");r.add("animallink.minio.secret-key",()->"minioadmin");r.add("animallink.minio.bucket",()->BUCKET);}
  @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired MinioClient minio;
  @BeforeEach void clean() throws Exception {if(!minio.bucketExists(BucketExistsArgs.builder().bucket(BUCKET).build()))minio.makeBucket(MakeBucketArgs.builder().bucket(BUCKET).build());STUB.volunteers.clear();STUB.volunteers.put(OWNER,"ACTIVE");STUB.volunteers.put(TARGET,"ACTIVE");STUB.volunteers.put(OTHER,"ACTIVE");STUB.animalDown=false;STUB.animalCalls=0;jdbc.update("DELETE FROM case_owner_audit_log");jdbc.update("DELETE FROM outbox_event");jdbc.update("DELETE FROM case_action_media");jdbc.update("DELETE FROM case_action");jdbc.update("DELETE FROM case_participant");jdbc.update("DELETE FROM animal_case");jdbc.update("DELETE FROM event_media");jdbc.update("DELETE FROM evidence_media");jdbc.update("DELETE FROM evidence");jdbc.update("DELETE FROM event");jdbc.update("DELETE FROM event_draft");}
  @AfterAll static void stop(){STUB.server.stop(0);}
  @Test void rescueListMapsStatesFiltersCountsAndKeepsSensitiveFieldsOut()throws Exception{seed("waiting","VERIFIED",null,null);seed("waiting-case","VERIFIED","ACTIVE","WAITING_CLAIM");String active=seed("active","VERIFIED","ACTIVE","CLAIMED");String resolved=seed("resolved","VERIFIED","RESOLVED","CLAIMED");seed("closed","VERIFIED","CLOSED","CLAIMED");seed("unresolved","VERIFIED","CLOSED_UNRESOLVED","CLAIMED");seed("cancelled","VERIFIED","CANCELLED","CLAIMED");seed("reported","REPORTED",null,null);evidence("e-waiting");action(active,null);action(resolved,"RESOLVED");mvc.perform(get("/api/v1/rescues").param("campusId",CAMPUS).param("size","20")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(7)).andExpect(jsonPath("$.items[?(@.eventId=='e-waiting')].rescueStatus").value("WAITING_CLAIM")).andExpect(jsonPath("$.items[?(@.eventId=='e-waiting-case')].rescueStatus").value("WAITING_CLAIM")).andExpect(jsonPath("$.items[?(@.eventId=='e-active')].rescueStatus").value("IN_PROGRESS")).andExpect(jsonPath("$.items[?(@.eventId=='e-resolved')].rescueStatus").value("COMPLETED")).andExpect(jsonPath("$.items[0].exactLocationDescription").doesNotExist()).andExpect(jsonPath("$.items[0].ownerUserId").doesNotExist());mvc.perform(get("/api/v1/rescues").param("campusId",CAMPUS).param("status","COMPLETED")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(4)).andExpect(jsonPath("$.items[?(@.eventId=='e-resolved')].resultCode").value("RESOLVED"));mvc.perform(get("/api/v1/rescues").param("campusId",CAMPUS).param("status","IN_PROGRESS")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(1)).andExpect(jsonPath("$.items[0].actionCount").value(1));}
  @Test void detailProjectsStatusesMediaAndEvidencePrivacy()throws Exception{String waiting=seed("detail-waiting","VERIFIED",null,null);String active=seed("detail","VERIFIED","ACTIVE","CLAIMED");String resolved=seed("detail-resolved","VERIFIED","RESOLVED","CLAIMED");seed("detail-reported","REPORTED",null,null);jdbc.update("UPDATE event SET exact_location_description='exact',latitude=1.1,longitude=2.2 WHERE id='e-detail'");jdbc.update("UPDATE animal_case SET owner_user_id=?,result_code='RESOLVED',result_summary='summary' WHERE id=?",OWNER,active);participant(active,TARGET,"ACTIVE");action(active,"RESOLVED");String evidence=evidence("e-detail",OTHER);eventMedia("e-detail");evidenceMedia(evidence);mvc.perform(get("/api/v1/rescues/e-detail-waiting")).andExpect(status().isOk()).andExpect(jsonPath("$.rescueStatus").value("WAITING_CLAIM"));mvc.perform(get("/api/v1/rescues/e-detail")).andExpect(status().isOk()).andExpect(jsonPath("$.rescueStatus").value("IN_PROGRESS")).andExpect(jsonPath("$.event.media[0].readUrl").exists()).andExpect(jsonPath("$.event.media[0].objectKey").doesNotExist()).andExpect(jsonPath("$.evidence[0].exactLocationDescription").doesNotExist()).andExpect(jsonPath("$.evidence[0].media[0].readUrl").exists()).andExpect(jsonPath("$.evidence[0].media[0].objectKey").doesNotExist()).andExpect(jsonPath("$.progress").isEmpty());mvc.perform(get("/api/v1/rescues/e-detail").header("X-User-Id",REPORTER)).andExpect(status().isOk()).andExpect(jsonPath("$.evidence[0].exactLocationDescription").value("x"));mvc.perform(get("/api/v1/rescues/e-detail").header("X-User-Id",OTHER)).andExpect(status().isOk()).andExpect(jsonPath("$.evidence[0].exactLocationDescription").value("x"));mvc.perform(get("/api/v1/rescues/e-detail").header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.event.exactLocationDescription").value("exact")).andExpect(jsonPath("$.evidence[0].exactLocationDescription").value("x")).andExpect(jsonPath("$.progress[0].resultCode").value("RESOLVED")).andExpect(jsonPath("$.viewer.canAddCaseAction").value(true));mvc.perform(get("/api/v1/rescues/e-detail").header("X-User-Id",TARGET)).andExpect(status().isOk()).andExpect(jsonPath("$.evidence[0].exactLocationDescription").value("x"));mvc.perform(get("/api/v1/rescues/e-detail-resolved")).andExpect(status().isOk()).andExpect(jsonPath("$.rescueStatus").value("COMPLETED"));mvc.perform(get("/api/v1/rescues/e-detail-reported")).andExpect(status().isOk()).andExpect(jsonPath("$.rescueStatus").doesNotExist());}
  @Test void detailSeparatesReporterOwnerParticipantAdminAndTerminalAccess()throws Exception{String c=seed("detail-matrix","VERIFIED","ACTIVE","CLAIMED");jdbc.update("UPDATE event SET exact_location_description='exact',latitude=1.1,longitude=2.2 WHERE id='e-detail-matrix'");participant(c,TARGET,"ACTIVE");action(c,"RESOLVED");mvc.perform(get("/api/v1/rescues/e-detail-matrix").header("X-User-Id",REPORTER)).andExpect(status().isOk()).andExpect(jsonPath("$.event.exactLocationDescription").value("exact")).andExpect(jsonPath("$.progress").isEmpty());mvc.perform(get("/api/v1/rescues/e-detail-matrix").header("X-User-Id",OTHER)).andExpect(status().isOk()).andExpect(jsonPath("$.event.exactLocationDescription").doesNotExist()).andExpect(jsonPath("$.progress").isEmpty());mvc.perform(get("/api/v1/rescues/e-detail-matrix").header("X-User-Id",TARGET)).andExpect(status().isOk()).andExpect(jsonPath("$.event.exactLocationDescription").value("exact")).andExpect(jsonPath("$.progress[0].resultCode").value("RESOLVED")).andExpect(jsonPath("$.viewer.canSubmitResult").value(true));participant(c,OTHER,"LEFT");mvc.perform(get("/api/v1/rescues/e-detail-matrix").header("X-User-Id",OTHER)).andExpect(status().isOk()).andExpect(jsonPath("$.event.exactLocationDescription").doesNotExist()).andExpect(jsonPath("$.progress").isEmpty());}
  @Test void detailCanClaimIsPublicAndQuietlyFailClosedAndAnimalFailureDegrades()throws Exception{seed("claimable","VERIFIED",null,null);mvc.perform(get("/api/v1/rescues/e-claimable").header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.viewer.canClaim").value(true));STUB.volunteers.put(OWNER,"PAUSED");mvc.perform(get("/api/v1/rescues/e-claimable").header("X-User-Id",OWNER)).andExpect(status().isOk()).andExpect(jsonPath("$.viewer.canClaim").value(false));STUB.animalDown=true;try{mvc.perform(get("/api/v1/rescues/e-claimable")).andExpect(status().isOk()).andExpect(jsonPath("$.animal.id").value("animal-claimable"));}finally{STUB.animalDown=false;}}
  @Test void listUsesOneBatchedAnimalRequestForManyRows()throws Exception{for(int i=0;i<4;i++)seed("batch-"+i,"VERIFIED",null,null);mvc.perform(get("/api/v1/rescues").param("campusId",CAMPUS).param("size","20")).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(4));assertEquals(1,STUB.animalCalls);}
  @Test void volunteerWorkspaceScopesAreRelationAndMembershipBound()throws Exception{String available=seed("available","VERIFIED",null,null);String owner=seed("owner","VERIFIED","ACTIVE","CLAIMED");jdbc.update("UPDATE animal_case SET owner_user_id=? WHERE id=?",OWNER,owner);String former=seed("former","VERIFIED","CANCELLED","CLAIMED");participant(former,TARGET,"LEFT");mvc.perform(get("/api/v1/volunteer/cases").header("X-User-Id",OWNER).param("campusId",CAMPUS).param("scope","AVAILABLE")).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].eventId").value("e-available")).andExpect(jsonPath("$.items[0].relationship").value("AVAILABLE"));mvc.perform(get("/api/v1/volunteer/cases").header("X-User-Id",OWNER).param("campusId",CAMPUS).param("scope","ACTIVE")).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].caseId").value(owner)).andExpect(jsonPath("$.items[0].relationship").value("OWNER"));mvc.perform(get("/api/v1/volunteer/cases").header("X-User-Id",TARGET).param("campusId",CAMPUS).param("scope","HISTORY")).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].caseId").value(former)).andExpect(jsonPath("$.items[0].relationship").value("FORMER_PARTICIPANT"));STUB.volunteers.put(OWNER,"PAUSED");mvc.perform(get("/api/v1/volunteer/cases").header("X-User-Id",OWNER).param("campusId",CAMPUS).param("scope","AVAILABLE")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("ACTIVE_VOLUNTEER_REQUIRED"));assertEquals("e-available",jdbc.queryForObject("SELECT id FROM event WHERE id=?",String.class,"e-available"));}
  private String seed(String suffix,String eventStatus,String caseStatus,String claim){Timestamp n=Timestamp.from(Instant.parse("2026-10-03T10:00:00Z"));String e="e-"+suffix,d="d-"+suffix,c="c-"+suffix;jdbc.update("INSERT INTO event_draft(id,user_id,campus_id,description,occurred_at,public_location_description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",d,REPORTER,CAMPUS,"draft",n,"public",n,n);jdbc.update("INSERT INTO event(id,source_draft_id,reporter_user_id,campus_id,animal_id,description,abnormality_summary,occurred_at,reported_at,public_location_description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",e,d,REPORTER,CAMPUS,"animal-"+suffix,"event", "abnormal",n,n,"public",eventStatus,n,n);if(caseStatus!=null)jdbc.update("INSERT INTO animal_case(id,event_id,campus_id,animal_id,owner_user_id,status,claim_status,claimed_at,created_at,updated_at,result_code,result_summary,result_submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",c,e,CAMPUS,"animal-"+suffix,"WAITING_CLAIM".equals(claim)?null:OWNER,caseStatus,claim,"WAITING_CLAIM".equals(claim)?null:n,n,n,"RESOLVED".equals(caseStatus)?"RESOLVED":null,"RESOLVED".equals(caseStatus)?"summary":null,"RESOLVED".equals(caseStatus)?n:null);return c;}
  private String evidence(String event){return evidence(event,REPORTER);} private String evidence(String event,String submitter){Timestamp n=Timestamp.from(Instant.now());String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO evidence(id,event_id,submitter_user_id,description,occurred_at,public_location_description,exact_location_description,latitude,longitude,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",id,event,submitter,"e",n,"p","x",1,2,n);return id;}
  private void eventMedia(String event)throws Exception{byte[] bytes="event-media".getBytes(StandardCharsets.UTF_8);String key="events/"+event+"/00.png";minio.putObject(PutObjectArgs.builder().bucket(BUCKET).object(key).stream(new ByteArrayInputStream(bytes),bytes.length,-1).contentType("image/png").build());Timestamp n=Timestamp.from(Instant.now());jdbc.update("INSERT INTO event_media(id,event_id,object_key,content_type,size_bytes,sort_order,created_at) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID().toString(),event,key,"image/png",bytes.length,0,n);}
  private void evidenceMedia(String evidence)throws Exception{byte[] bytes="evidence-media".getBytes(StandardCharsets.UTF_8);String key="evidence/"+evidence+"/00.png";minio.putObject(PutObjectArgs.builder().bucket(BUCKET).object(key).stream(new ByteArrayInputStream(bytes),bytes.length,-1).contentType("image/png").build());Timestamp n=Timestamp.from(Instant.now());jdbc.update("INSERT INTO evidence_media(id,evidence_id,object_key,content_type,size_bytes,sort_order,created_at) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID().toString(),evidence,key,"image/png",bytes.length,0,n);}
  private void action(String c,String result){Timestamp n=Timestamp.from(Instant.now());jdbc.update("INSERT INTO case_action(id,case_id,actor_user_id,description,occurred_at,created_at,result_code) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,OWNER,"action",n,n,result);}
  private void participant(String c,String user,String state){Timestamp n=Timestamp.from(Instant.now());jdbc.update("INSERT INTO case_participant(id,case_id,user_id,status,invited_by_user_id,invited_at,joined_at,ended_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),c,user,state,OWNER,n,n,"ACTIVE".equals(state)?null:n,n,n);}
  static class Stub {final HttpServer server;final Map<String,String> volunteers=new ConcurrentHashMap<>();volatile boolean animalDown;volatile int animalCalls;Stub(){try{server=HttpServer.create(new InetSocketAddress(0),0);server.createContext("/",this::handle);server.start();}catch(IOException e){throw new RuntimeException(e);}}String url(){return "http://localhost:"+server.getAddress().getPort();}void handle(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath(),u=e.getRequestHeaders().getFirst("X-User-Id");if(p.contains("animals/batch")){animalCalls++;if(animalDown){e.sendResponseHeaders(503,-1);e.close();return;}}String[] parts=p.split("/");String subject=parts.length>4?parts[4]:u;String out=p.contains("volunteer-membership")?("ACTIVE".equals(volunteers.get(subject))?"{\"exists\":true,\"active\":true,\"status\":\"ACTIVE\"}":"{\"exists\":true,\"active\":false,\"status\":\"PAUSED\"}"):p.contains("animals/batch")?"[]":"{\"id\":\""+u+"\",\"systemRole\":\""+(ADMIN.equals(u)?"GOVERNANCE_ADMIN":"USER")+"\"}";byte[] body=out.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(200,body.length);e.getResponseBody().write(body);e.close();}}
}
