package org.animallink.animal.infrastructure;

import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import java.sql.Timestamp; import java.time.Instant; import java.time.format.DateTimeParseException; import java.util.UUID; import org.springframework.amqp.AmqpRejectAndDontRequeueException; import org.springframework.amqp.rabbit.annotation.RabbitListener; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;

@Component @ConditionalOnProperty(name="animallink.messaging.enabled",havingValue="true",matchIfMissing=true)
public class AdoptionCompletedAnimalConsumer {
 private final JdbcTemplate jdbc; private final ObjectMapper json; public AdoptionCompletedAnimalConsumer(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 @RabbitListener(queues="animal.timeline.adoption-completed") @Transactional public void consume(String message){JsonNode p=parse(message);Event e=validate(p);if(jdbc.update("INSERT IGNORE INTO processed_domain_event(event_id,event_type,processed_at) VALUES(?,?,?)",e.eventId(),"ADOPTION_COMPLETED",Timestamp.from(Instant.now()))==0)return;int changed=jdbc.update("UPDATE animal SET adoption_status='ADOPTED',current_context='ADOPTED_HOME',version=version+1 WHERE id=? AND identity_status='ACTIVE' AND adoption_status='OPEN' AND current_context='CAMPUS'",e.animalId());if(changed!=1)reject("invalid animal adoption state");jdbc.update("INSERT INTO timeline_entry(id,animal_id,source_type,source_id,entry_type,title,summary,occurred_at,visibility,created_at) VALUES(?,?,'ADOPTION',?,'ADOPTION_COMPLETED','已完成领养交接',NULL,?,'PUBLIC',?)",UUID.randomUUID().toString(),e.animalId(),e.relationId(),Timestamp.from(e.occurredAt()),Timestamp.from(Instant.now()));}
 private Event validate(JsonNode p){String event=text(p,"eventId"),type=text(p,"eventType"),relation=text(p,"relationId"),handover=text(p,"handoverId"),animal=text(p,"animalId"),occurred=text(p,"occurredAt");if(event==null||!"ADOPTION_COMPLETED".equals(type)||p.path("eventVersion").asInt()!=1||relation==null||handover==null||animal==null||occurred==null)reject("invalid ADOPTION_COMPLETED contract");try{return new Event(UUID.fromString(event).toString(),UUID.fromString(relation).toString(),UUID.fromString(handover).toString(),UUID.fromString(animal).toString(),Instant.parse(occurred));}catch(IllegalArgumentException|DateTimeParseException x){throw new AmqpRejectAndDontRequeueException("invalid ADOPTION_COMPLETED contract",x);}}
 private JsonNode parse(String s){try{return json.readTree(s);}catch(Exception x){throw new AmqpRejectAndDontRequeueException("invalid ADOPTION_COMPLETED payload",x);}} private static String text(JsonNode n,String k){return n.hasNonNull(k)&&!n.get(k).asText().isBlank()?n.get(k).asText():null;} private static void reject(String message){throw new AmqpRejectAndDontRequeueException(message);} private record Event(String eventId,String relationId,String handoverId,String animalId,Instant occurredAt){}
}
