package org.animallink.animal.infrastructure;

import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import java.sql.Timestamp; import java.time.Instant; import java.time.format.DateTimeParseException; import java.util.Set; import java.util.UUID; import org.springframework.amqp.AmqpRejectAndDontRequeueException; import org.springframework.amqp.rabbit.annotation.RabbitListener; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.dao.DuplicateKeyException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;

@Component @ConditionalOnProperty(name="animallink.messaging.enabled",havingValue="true",matchIfMissing=true)
public class CaseResultTimelineConsumer {
 private final JdbcTemplate jdbc; private final ObjectMapper json; public CaseResultTimelineConsumer(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 @RabbitListener(queues="animal.timeline.case-result") @Transactional public void consume(String message){JsonNode p=parse(message);String outcome=text(p,"outcome"),animal=text(p,"animalId"),caseId=text(p,"caseId"),occurred=text(p,"occurredAt");if(text(p,"eventId")==null||!"CASE_RESULT_FINALIZED".equals(text(p,"eventType"))||p.path("eventVersion").asInt()!=1||caseId==null||animal==null||!Set.of("RESOLVED","UNRESOLVED","CANCELLED").contains(outcome)||occurred==null)reject();String title=switch(outcome){case "RESOLVED"->"救助处理已解决";case "UNRESOLVED"->"救助处理未解决";default->"救助处理已取消";};try{jdbc.update("INSERT INTO timeline_entry(id,animal_id,source_type,source_id,entry_type,title,summary,occurred_at,visibility,created_at) VALUES(?,?,'CASE',?,'RESCUE_RESULT',?,?,?,'PUBLIC',?)",UUID.randomUUID().toString(),animal,caseId,title,text(p,"summary"),Timestamp.from(parseInstant(occurred)),Timestamp.from(Instant.now()));}catch(DuplicateKeyException e){String detail=String.valueOf(e.getMostSpecificCause().getMessage());if(!detail.contains("uk_timeline_source"))throw e;}}
 private JsonNode parse(String value){try{return json.readTree(value);}catch(Exception e){throw new AmqpRejectAndDontRequeueException("invalid CASE_RESULT_FINALIZED payload",e);}}
 private static Instant parseInstant(String value){try{return Instant.parse(value);}catch(DateTimeParseException e){throw new AmqpRejectAndDontRequeueException("invalid CASE_RESULT_FINALIZED occurredAt",e);}}
 private static void reject(){throw new AmqpRejectAndDontRequeueException("invalid CASE_RESULT_FINALIZED contract");}
 private static String text(JsonNode n,String k){return n.hasNonNull(k)&&!n.get(k).asText().isBlank()?n.get(k).asText():null;}
}
