package org.animallink.incident.infrastructure;

import java.util.List; import java.util.Map; import java.util.concurrent.TimeUnit;
import org.springframework.amqp.core.MessageDeliveryMode; import org.springframework.amqp.rabbit.connection.CorrelationData; import org.springframework.amqp.rabbit.core.RabbitTemplate; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Component; import org.springframework.transaction.support.TransactionTemplate;

@Component @ConditionalOnProperty(name="animallink.messaging.enabled",havingValue="true",matchIfMissing=true)
public class CaseResultOutboxPublisher {
 private final JdbcTemplate jdbc; private final RabbitTemplate rabbit; private final TransactionTemplate transactions;
 public CaseResultOutboxPublisher(JdbcTemplate jdbc,RabbitTemplate rabbit,TransactionTemplate transactions){this.jdbc=jdbc;this.rabbit=rabbit;this.transactions=transactions;}
 @Scheduled(fixedDelay=1000) public void publish(){publishBatch();}
 public int publishBatch(){List<String> ids=jdbc.queryForList("SELECT id FROM outbox_event WHERE status='PENDING' AND available_at<=CURRENT_TIMESTAMP(6) ORDER BY created_at,id LIMIT 20",String.class);int sent=0;for(String id:ids)if(Boolean.TRUE.equals(transactions.execute(status->publishLocked(id))))sent++;return sent;}
 private boolean publishLocked(String id){List<Map<String,Object>> rows=jdbc.queryForList("SELECT id,payload_json FROM outbox_event WHERE id=? AND status='PENDING' AND available_at<=CURRENT_TIMESTAMP(6) FOR UPDATE SKIP LOCKED",id);if(rows.isEmpty())return false;try{CorrelationData correlation=new CorrelationData(id);rabbit.convertAndSend("animallink.domain","incident.case.result-finalized",rows.getFirst().get("payload_json").toString(),message->{message.getMessageProperties().setDeliveryMode(MessageDeliveryMode.PERSISTENT);message.getMessageProperties().setContentType("application/json");return message;},correlation);CorrelationData.Confirm confirm=correlation.getFuture().get(5,TimeUnit.SECONDS);if(!confirm.isAck())throw new IllegalStateException(confirm.getReason()==null?"broker nack":confirm.getReason());/* A crash after this ACK but before the DB update can redeliver; the consumer's source uniqueness provides at-least-once idempotency. */jdbc.update("UPDATE outbox_event SET status='PUBLISHED',published_at=CURRENT_TIMESTAMP(6),last_error=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='PENDING'",id);return true;}catch(Exception e){String error=String.valueOf(e.getMessage());if(error.length()>1000)error=error.substring(0,1000);jdbc.update("UPDATE outbox_event SET attempt_count=attempt_count+1,last_error=?,available_at=CURRENT_TIMESTAMP(6)+INTERVAL 5 SECOND,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='PENDING'",error,id);return false;}}
}
